### ISSUE TITLE
Digitaalse ühisturu andmete vaba liikumise konverents 17.07.2017

### ISSUE THREAD

**Issue by boamaod** [okestonia/esindus#1]
Kavatseme osaleda 17. juulil 2017 toimuva digitaalse ühisturu andmete vaba liikumise konverentsi ("DSM konverents") ettevalmistamisel ja korraldamisel partnerina. Konverentsi eesmärk on hoida ülal Eesti mainet andmete vaba liikumise eestkõnelejana ning hoida teemat aktuaalsena Euroopa Liidus ja julgustada teisi liikmesriike antud teemaga aktiivselt tegelema. Meie seisame seal kodanikukeskse andmekasutuse ja oma põhikirjalise eesmärgi eest "tagada info vaba kättesaadavus kõigis ühiskonna kihtides, nii era- kui avalikus sektoris".

**Comment by infokujur** [comment]
OKE oli kohal. Mydata2017 konverentsil antakse edasi nägemus inimkeskse andmekäsitluse visioon MyData deklaratsiooni raames. Teemaga tegeletakse edasi.
#17
