### ISSUE TITLE
Slack'iga liitumine

### ISSUE THREAD

**Issue by tormi** [okestonia/esindus#11]
Hei, äkki saaks liitumise hõlbustamiseks kasutusele võtta https://github.com/rauchg/slackin ?

**Comment by tormi** [comment]
One can easily deploy Slackin to Heroku, see:
- https://github.com/rauchg/slackin#usage (Heroku link)
- https://medium.com/@abhaytalreja/slackin-slack-signup-button-for-free-7126e35d4956#.igkudvssu

**Comment by infokujur** [comment]
Anyhow - before things will be set up just send an email to kontakt@opendata.ee and we will send an invitation back.

**Comment by infokujur** [comment]
#4 Nagu selle teema sulgemisel öeldud. Kui vaja edasi tegeleda, siis palun avame uue teema. Kui keegi võtab kasutusele, siis igasugu integratsioonid on teretulnud. Praegu oleme Slack / Github / Skype combos ja iga projekt eraldi vastavalt oma kanalitele.
