### ISSUE TITLE
Members of Open Knowledge Estonia NGO

### ISSUE THREAD

**Issue by Hillehinsberg** [okestonia/esindus#13]
MTÜ Open Knowledge Estonia liikmeavalduse esitanud ja juhatuse otsusega liikmeks vastu võetud on järgmised isikud ja organisatsioonid. 
This is  a regularly updated list of official members of OK-EE

Siim Tuisk
Heikki Visnapuu
Risto Hinno
Adolfo Ruiz Calleja
Edmund Laugasson
Andi Hektor
DataMe OÜ - represented by Marko Vaik
Register OÜ - represented by  Peep Küngas
Stats Unities OÜ  - represented by Oliver Kadak 
 Open Knowledge Finland -  represented by  Antti J Poikola
Citizen OS (Teeme Ära SA)  - reprsented by Margo Loor

**Comment by tormi** [comment]
Duplicate of #6?
