### ISSUE TITLE
Rufus Pollock in Estonia events around Sep 12th 2017

### ISSUE THREAD

**Issue by boamaod** [okestonia/esindus#16]
Rufus Pollock is giving a keynote at [YES conference](https://yes2017.riigikontroll.ee/program/) on Sep 12th in Tallinn and OK-EE is planning to organise public/meetings or other events with Dr Pollock in similar manner to [his last visit in Sep 2016](http://opendata.ee/et/blog/rufus-pollock-making-an-open-information-society/), which lead to [founding of OK-EE](https://ee.okfn.org/et/oleme-avatud/).

Feel free to give your ideas or join in organising the events.

**Comment by infokujur** [comment]
#17

**Comment by infokujur** [comment]
Loeng + seminar.
Anname teemad (korjame liikmetelt) ja küsime, mis tema meie kohta soovib teada.
Korjame teemasid Üldkoosolekule.
Kuupäev paika ASAP.

**Comment by boamaod** [comment]
* Do we organise something like that on 10th? It would be OK-EE activists and partners mostly. Who would they be? Garage48? http://open-leaders.com/
* On the evening of 12th we will have meetup with everybody interested and open knowledge members: https://www.facebook.com/events/2094056934155199/
* Who should Rufus meet in private to promote open agenda?

**Comment by infokujur** [comment]
Meeting today: https://www.facebook.com/events/2094056934155199/?acontext=%7B%22action_history%22%3A%22[%7B%5C%22surface%5C%22%3A%5C%22page%5C%22%2C%5C%22mechanism%5C%22%3A%5C%22page_upcoming_events_card%5C%22%2C%5C%22extra_data%5C%22%3A[]%7D]%22%2C%22has_source%22%3Atrue%7D

**Comment by infokujur** [comment]
Maarja-Leena will add information to the slides presented in the meetup and add topics to the agenda of the General Meeting.
#22
