### ISSUE TITLE
Andmeajakirjandus - Shool of Data programmi Eestisse toomine - Info koondamine

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#19]
Maarja-Leena on andnud nõusoleku teha koostööd BFM / TLU-ga ja loonud suhted School of Data Latvia-ga.

- Kas on veel huvilisi ja osapooli?
- Vaja organiseerida kohtumine School of Data Latviaga ning luua metoodika tutvustus huvitatutele.
- Uurida OKI rahastusvõimalusi

**Comment by infokujur** [comment]
#17

**Comment by infokujur** [comment]
MEDITi ja TLUga endiselt kontaktis, sisse antud taotlustest veel õnnestumisi ei ole. Teema endiselt orbiidil.
Jälgime põnevusega, mis toimub Issue tracker'is meedi teemadel.
https://github.com/okestonia/opendata-issue-tracker/issues?q=is%3Aopen+is%3Aissue+label%3AERR

**Comment by peepkungas** [comment]
Andmeajakirjandus on Register OÜ jaoks samuti oluline teema. Alustasime hiljuti eraldi projektiga, mille raames hakkame inforegister.ee-sse andmeajakirjanduse sisu tootma ettevõtluse vaatevinklist. Meie huviks on arendada võimekust andmeid paremini ära kasutada lugude rääkimise seisukohast. Kui näete koostöös jumet, siis andke märku.

**Comment by infokujur** [comment]
@peepkungas Meil toimub pisike töötuba, kus proovime ühe säästva arengu eesmärgiga mäele saada.
Lisainfo siin: https://github.com/okestonia/opendata-issue-tracker/issues/93

Töötoas lööb kaasa Teemo YLEst. Usun, et on kasulik kontaktpunkt. Ootan ka huviga, kes meilt kohale tulevad.

**Comment by infokujur** [comment]
Sulgen selle kui dublikaadi. Räägime selles teises teemas edasi. Shool of Data-ga praegu otseselt ei tegele. Kui sinna tulevad konkreetsed tegevused otsa, siis avame uuesti.
