### ISSUE TITLE
Eesti kiirkorras viimine Open Data indeksisse

### ISSUE THREAD

**Issue by boamaod** [okestonia/esindus#2]
On oodatud meie organisatsiooni pädevate aktivistide sisend suurde kodanikuühiskonna poolt ülal peetavasse Open Data indeksisse:

* http://global.survey.okfn.org/

Tähtaeg sisendi andmiseks on 15.12.2016, täita saab seda mugavalt veebivormis ja enne täitmist peaks lugema, et mis põhiasju täitmisel silmas pidada:

* http://global.survey.okfn.org/methodology/ (jt lingid seal lehel)

Ma ühes meilis kirjeldasin seda ülesannet nii:

> Üldiselt on vaja teha hunnik linnukesi ja ristikesi seoses sellega, et mis andmekogud on ligipääsetavad avatult ja mis pool-avatult (sisselogimised, captchad jmt) ja mis lausa rahamüüri vmt taga, mis formaadis on andmed ligipääsetavad (sj kas see on avatud formaat), kas on lihtsalt leitavad (kodulehel eraldi avaandmete kataloogis nagu AvTS seda nõuab), kas litsents on selgelt välja toodud (seda pole ma veel kuskil selgelt näinud, nt kultuuriväärtusi puudutavatel materjalidel arhiivides on sageli juhuslikud/valed litsentsid), kas andmed on töödeldavad masinaga (kui on PDF või DOC, siis on raskustega, sest need formaadid pole selleks ette nähtud), kas mugavaks töötlemiseks on ühes failis tervikuna allalaaditavad jne.
>
> Open Data Index pakub avaandmete seisu analüüsimiseks jaoks universaalset metoodikat. Kõige alus on Open Definition, mis on tõlgitud ka eesti keelde:
>
> * http://opendefinition.org/od/2.1/et/

**Comment by Hillehinsberg** [comment]
Ma võtan enda ülesandeks Government Budget, Government Spending ja Draft Legislation

**Comment by boamaod** [comment]
Kas keegi võtaks vaevaks küsida, et kuidas selle 15. detsembri tähtajaga on, et kas saab hilinemisega ka materjale esitada erandkorras?

**Comment by Hillehinsberg** [comment]
Esitasin enne 15.dets tähtaega ära 3 teemat - government budget, government spending ja national statistics.  Olen valmis neid täiendama, kui review etapis selleks  vajadus tekib.

**Comment by boamaod** [comment]
Kõige viimane _deadline_ kõige viimaste _deadline_'ide seas on 20.01.2017, st järgmine reede. Selleks ajaks peaks me sisendid läbi arutama ja viimased pingutused tegema. Sobib?

**Comment by infokujur** [comment]
Siit tuleb sisend järgmisel võimalusel:
https://github.com/okestonia/Estonian-Open-Data-Issue-Tracker

**Comment by infokujur** [comment]
@boamaod Kas Sa tead, millal tuleb uus võimalus andmeid sisestada? Selle vana teema sulgeme ja avame siis kui uus rong tuleb.
