### ISSUE TITLE
Mydata 2017 konverentsi järelsisu - artiklid Sirpi

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#20]
Aktiivne konverentsi korraldamise töö käib. Kas kirjutame oktoobriks Sirbi artikleid? Artiklid väga vajalikud. Järelsisu loomise vajalikkus. Mis ideed ja vajadused meil võiksid olla?
2018 konverents toimub. Kuupäevad jäävad samaks - augusti viimane nädal. Hõigatakse välja. Toimumiskoht ei ole veel kindel.

**Comment by infokujur** [comment]
#17

**Comment by infokujur** [comment]
@tanelmallo Kas see teema on nüüd kinni?

**Comment by tanelmallo** [comment]
Ei ole kinni. Uus plaan on toota sisu maikuuks.
Tanel


---
Tanel Mällo | MyData2018 Programme
phone: +372 5211 371 (Estonia)
visit MyData conference: mydata2018.org
join MyData network on Slack: mydata.org/slack/
sign MyData Declaration: mydata.org/declaration/ and use the badge below

**Comment by tanelmallo** [comment]
Septembris jõuab Sirpi intervjuu Paul-Olivier Dehaye (PersonalData.IO) ja Katryna Dow'ga (Meeco.me), teemaks isikuandmed, GDPR ja demokraatia.

**Comment by infokujur** [comment]
Siin tegevust ei toimunud.
