### ISSUE TITLE
Avandmete olukorra kirjeldus KOV tasandil

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#23]
Peale haldusreformi on vaja teha suuri ümberkorraldusi ITsüsteemides.
Vaja on juhtida tähelepanu avaandmetele.

Tegelevad Hille ja Märt.

**Comment by infokujur** [comment]
#17

**Comment by tormi** [comment]
Kõige mõistlikum on selle teemaga alustada siit (v.a. Tallinn, jt suuremad, kellega tuleks tegeleda otse): http://kov.riik.ee/kontaktid/

**Comment by boamaod** [comment]
Põhimõtteliselt sisaldaks see järgnevaid teese:

* Vanade infosüsteemide sisu kättesaadavaks tegemine avaandmete kataloogis on oluline, aga on arusaadav, kui see toimub mingi kindla ajakava alusel ja ressursse mõistlikult panustades.
* Andmete esmane ülespanek kataloogi on väikese kuluga ülesanne ja esimese sammu peaks tegema kohe ning
** avaldama andmekogud mille andmebaasi ühekordse väljavõtte tegemine vm eksport nt ühekuulise vm pikema intervalli tagant pole ülemäära koormav;
** leppima linna/vallavalitsuses kokku esialgse vastutaja ja kontakti avaandmete teemadel, kes hakkab jälgima https://github.com/okestonia/opendata-issue-tracker ettepanekuid ning koguma idufirmade, kodanike, ülikoolide jt ettepanekuid andmete osas, neile vastama ning uuendama avaandmete kataloogi täiendamise ajakava.
* Iga uue infosüsteemi puhul on andmesisu jaoks korrektse seadusele vastava avaandmete kataloogi loomine kohustuslik ning seaduse täitmata jätmine on alus täidesaatva võimu sekkumiseks seaduse rikkumise lõpetamiseks või ettevõtetele, eraisikutele jt huvitatud osapooltele hagemiseks seaduse eiramisest tuleneva majandusliku kasu hüvitamiseks.
* Avaandmete kataloogid tuleks ehitada üles lähtuvalt inimkeskse andmekasutuse põhimõtetest.
* Avaandmete kataloogid peaks põhinema riiklikel soovitustel https://opendata.riik.ee/et/juhendid ning taaskasutataval modulaarsel tarkvaral, mis teeb andmed standardsete APIde kaudu kättesadavaks, päritavaks ja ülekantavaks jne.
* Avaandmete kataloogis sisalduvad andmed peavad olema korrektselt koos litsentside ja andmestruktuuride versiooni infoga registreeritud riigi avaandmete portaalis https://opendata.riik.ee/.
* Open Knowledge on valmis võtma endale kogukonna, st idufirmade, kodanike, ülikoolide jt ning omavalitsuste omavahelise suhtluse vahendamise, koondama ettepanekuid ning andma soovitusi avaandmete kataloogide loomise korraldamise tehniliste lahenduste ja ajakava osas.

Lisaks sellele peaks dokumenti panema võrdluse Soome/Helsingiga andmete kasutuse osas (statistika) ja mingid viited uuringutele, mis kinnitavad, et avaandmed on majanduslikult kasulikud, esialgsed viited:

* http://www.digar.ee/arhiiv/nlib-digar:132075 (eestis hinnanguliselt ootab avalikustamist 20 000 andmekogu)
* http://vm.fi/julkaisu?pubid=6902 (avoimen tiedon ohjelman 2013-2015 loppuraportti, sj ingliskeelne kokkuvõte)
* http://www.thegovlab.org/static/files/publications/open-data-impact-key-findings.pdf (siit midagi üldarusaadavat mõjude kohta?)
* https://www.europeandataportal.eu/sites/default/files/edp_creating_value_through_open_data_0.pdf (üks vanem uuring mõju kohta euroopas)
* https://theodi.org/diverse-uk-companies-open-data (uk kogemusest --- "open data means business")

Kõigele lisaks tasuks massiivselt Andrus Ansipit tsiteerida.

**Comment by boamaod** [comment]
Statistikat:

Helsingi -- http://www.hri.fi

* 609 andmehulka -- http://www.hri.fi/en/dataset
* 188 rakendust -- http://www.hri.fi/en/applications

Kas keegi uurib välja mitu konkurssi on Helsingi on korraldanud/sponsoreerinud ja mitu rakendust on seal tehtud?

* https://www.citylab.com/life/2014/04/how-helsinki-mashed-open-data-regionalism/8994/
* http://www.hri.fi/en/news/open-data-as-a-key-element-for-transparency/
* https://www.nbforum.com/newsroom/blog/helsinki-forerunner-open-data/

Kontaktid leiab: http://www.hri.fi/en/about/contact-information/

Eesti statistika:

Tartu -- https://www.tartu.ee/et/avaandmed
19 andmehulka

Tallinn -- http://avaandmed.tallinn.ee/
20 andmehulka

Pärnu -- https://amphora.lv.parnu.ee/amphora_public/?o=39&o2=123029&u=-1&hdr=od&tbs=all
4 andmehulka

Rakendused:

* http://tallinnraiub.ee/
* ...

Kas siit on veel mõni KOV puudu?

Hinnangud:

* omavalitsused ei täida seadust ja süüdi on selles osaliselt ka riik, kes ei näita eeskuju ega tee selgitustööd, sh pole eraldanud ressursse MKM avaandmete tegevuskava elluviimiseks (plaanitud ametikohad täitmata jne)
* opendata.riik.ee kirjed on sageli fiktiivsed ja keegi ei halda neid, ei kustuta valesid kirjeid, ei uuenda CKAN baastarkvara ja mooduleid
* Eesti tase avaandmete indeksites on EL riikide teises pooles ja see on isegi positiivne hinnang (eksperdid on andnud indeksitele sisendit, mis pole alati täpne, nt on väidetud, et x-tee asendab avaandmed jne)

**Comment by boamaod** [comment]
Täiendav idee: saadame koos selle dokumendiga suurimates omavalitsustes kandieerivatele erakondadele ja valimisliitudele konkreetselt formuleeritud viis küsimust, et kuidas nad kavatsevad nende asjadega pärast valimisi tegeleda.

**Comment by infokujur** [comment]
Kui konkreetsete andmehulkade osas tuleb infot, siis palun dokumenteerige siia: https://github.com/okestonia/opendata-issue-tracker/issues

Ja sildistage "Local Auth". Siis edaspidi saab seda tegevusliini (andmekogude ja haldajate/vastutajate lõikes) seal jälgida.

**Comment by Hillehinsberg** [comment]
Ma olen liituvate KOVide olukorrast aru saanud nii, et kõige esmasem probleem igasugu andmekogudega on turvalisus. Seega vajavad KOVid  abi (enamusel pole infosüsteemide  teemal pädevust ega inimest)  ja nõu, kuidas ühelt poolt kaitsta andmeid ja teisalt  avada - kuidas teha  õige liigitus.

Esiteks on palju andmeid kohalike elanike kohta, mida  ei peagi haldama KOVid vaid  riik, nt ehitisregister, sotsiaaltoetuste süsteemid STAR ja SKAIS – siin on vaja uutel KOVidel juurdepääsu ja õigusi hallata.  Andmete avamise üle nad ei otsusta.

Teist  tüüpi hoiab Andmevara, kontrollib  teenuse kvaliteeti ja pakub ka digitaalset menetlust (sh eeltäidetud teenuse taotlemise vorme). 
Kolmas  tüüp: KOV peaks ise haldama, aga tegelikkuses on need andmekogud teenusepakkujate käes. 
Siin on kõige keerukam olukord.

**Comment by boamaod** [comment]
Üldkoosolekul selgus, et õigete litsentside kasutamist tuleks igal juhul õigel ajal rõhutada, sest kui litsentsipimedus maad võtab, siis tagantjärele on seda peaaegu võimatu parandada. Ametlikult soovitatav litsents on:

> Avaandmete hulgal peab olema litsents, mis võimaldab tema vaba, piiranguteta kasutamist, töötlemist ja levitamist, sealjuures võimaldama levitamist kasutaja valikul nii tasuta kui tasu eest.
>
> Eelsitatult soovitame litsentsiks valida Creative Commons litsentsi, vt täpsemalt https://creativecommons.org/. Sealloetletud litsentsidest soovitame eeskätt CC by 3.0 litsentsi: https://creativecommons.org/licenses/by/3.0/

https://opendata.riik.ee/et/kkk

**Comment by infokujur** [comment]
Litsenseerimine sai endale oma _issue_ https://github.com/okestonia/esindus/issues/33

**Comment by infokujur** [comment]
@infokujur tegeleb teemaga kaudselt avaandmete infopäeva raames.
Tulemuse lingin siia. 
https://github.com/okestonia/opendata-issue-tracker/issues/95

**Comment by infokujur** [comment]
Eemaldan @Hillehinsberg - kuna ta enam ei ole juhatuses ja teemasid ei vea. Liikmena räägib kaasa.

**Comment by infokujur** [comment]
Tegevusi ei ole planeeritud ja vedajat ei ole. Sulgen, kuni tekib vedaja.
