### ISSUE TITLE
Avaandmete päev / Open Data Day 2018

### ISSUE THREAD

**Issue by boamaod** [okestonia/esindus#24]
Because of administrative reform for municipalities one reasonable topic is open data in municipalities. Probably it's reasonable to conduct this part mainly in Estonian and ask municipalities to join. What about English part, any special focus for that?

Tundub, et seekord võiks teha ühe suurema konverentsi vmt ürituse just KOV avaandmete teemal. Kui tahta KOVe endid osalema, siis peab selle tegema vist eesti keeles. Vt täpsemalt #23.

Avaandmete päevast: https://en.wikipedia.org/wiki/International_Open_Data_Day

**Comment by boamaod** [comment]
Avaandmete päev on sel aastal 3. märtsil, tundub, et ametlik fookus on avatud teadusandmed, avalike rahavoogude jälgimine ja avatud geoinfo:

* http://opendataday.org/#what
* https://blog.okfn.org/2017/12/11/open-data-day-3-march-2018-you-are-invited/

 Tundub, et sündmuse veebikuvand jäetakse sel aastal samaks, seega peaksime Eesti sündmuse jaoks uuendama veebi:

* http://opendata.ee/opendataday/et/

Kuna OK-EE hakkab sellest aastast riigi tellimusel vedama avaandmete arendamist, siis sobiks see päev selle kickoffiks, kus me saaks tutvustada oma lähtepositsioone, meie käsutuses olevaid ressursse, võimalike roadmappe ja seda kõike andmete avaldajate ning lõppkasutajatega läbi rääkida.

**Comment by boamaod** [comment]
Hetkeseis on selline, et ma püüan siis ikka 3. märtsiks mingid ruumid nt 4h pikkuseks ajaks leida ja siis otsustame juba täpsemalt, mis teemad me tõstatame. Seni olen käinud välja:

* OKEE ja riigihanke kava, sh riigi avaandmete portaali tulevik
* Teabenõuete portaali prototüübi tutvustus (koostöö Transparency Estonia/Finlandiga, tarkvara Open Knowledge Germanylt)
* Wikimedia koostööprojektid mäluasutustega ja Eesti andmekogude liidestamine Wikidataga
* KOV taseme avaandmete küsimused (vt ka #23) ja üldse avaandmed asutustes, mis ei taha tingimata ise suurt taristut üles ehitada (neile on vaja mingeid juhendeid või tehnilisi soovitusi ilmselt)

Mis veel? Kes tahaks üles astuda või midagi arutada? Mis teemal? Geoandmete seis? Uued ägedad avalikud andmekogud 2017-2018? Mis nende rahavoogude andmetega ja teadusandmetega on -- kui me tahaks rahvusvahelise avaandmete päeva teemapüstitusega haakida?

**Comment by peepkungas** [comment]
Ma tooksin sisse linkandmete teema. Konkreetsed näited on DBPedia ja Register Graph API. Võibolla on neid veel tekkinud vahepeal...

**Comment by boamaod** [comment]
Käisin Tallinna linnaga rääkimas, ilmselt saadavad nad ühe inimese oma asjade seisu tutvustama ja vast tuleb tööle võetud kaasamisnõunik ka. Kas võiks püüda teistest omavalitsustest ja/või linnade liidust ka kedagi kutsuda?

**Comment by boamaod** [comment]
Avaandmete päev toimub 3. märtsil K-space.ee ruumides Akadeemia tee 21/a 5. korrusel kl 12-16, nüüd on olemas ka FB sündmus:

* https://www.facebook.com/events/145482652814998/

Kas leidub keegi, kes tahaks veebilehe uuendada? Tegelikult võiks teha ülevaate 2017. aastal avaldatud olulistest uutest andmekogudest -- kutsume rääkima avaldaja ja/või kasutaja? Kiireks läheb, aga äkki keegi teab, kede meelitada?

**Comment by boamaod** [comment]
Nüüd on ka veebileht uuendatud (eesti keeles ja in English): http://opendata.ee/opendataday/

**Comment by tanelmallo** [comment]
Sündmus toimus, ruum oli paksult rahvast täis ning videosalvestused on järelvaadatavad: https://www.facebook.com/events/145482652814998/
