### ISSUE TITLE
Social Impact Data Hack 2017 10-12 November, Tartu

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#25]
Page for the event: http://sidh2017.ut.ee/

Open Knowledge Estonia will help to get the data out!
https://github.com/okestonia/opendata-issue-tracker

**Comment by peepkungas** [comment]
Inforegister will propose a topic to SIDK 2017 for construction of a model for automatically detecting corruption cases from temporal networks of organizations, persons and assets (tenders, real estate, ...).

We can provide the following data:
1) Board members and owners of businesses
2) Some features of businesses
3) Real estate ownership data

In addition we will benefit from the following:
1) Public tender data (sums, descriptions and winners of tenders)
2) Public sector officials/employees 
3) Corruption cases (specific organizations and persons) for learning

Some time ago in the context of opener.ee project public tender receords were collected for years 2013-2015. Is there any update on this data?

Are there any options for getting the lists of public sector officials and corruption cases?

Also, anyone interested in participation? Contact me (peep.kungas@ir.ee).

**Comment by infokujur** [comment]
Results here: http://sidh2017.ut.ee/blog/
