### ISSUE TITLE
1. Overview of activities of OK-EE

### ISSUE THREAD

**Issue by tanelmallo** [okestonia/esindus#27]
#22 
Maarja-Leena: events and initiatives that we have participated in or organized.
* Open Data Day in Tartu. Important, that by open data people just mean data that is publicly accessible.
* Data as remedy: 24h post-truth hackathon. 60 people started. Six teams produced somethinginterdisciplinary, most participants were students; good mentoring.
* Open Data Issue Tracker opening. It happened in preparation to the G48 Baltic Open and Big Data Hackaton. It will also feed into the Estonian Open Data Index. Great help from Andres Kütt. Datasets from institutions who have never thought about data sharing before: AKI, Riigikontroll etc...
* MyData2017 Conference. This is the most intensive collaboration that we have with Finnish Open Knowledge. Finns are doing great work that we take as an example.
* TODAY'S meeting

UPCOMING EVENTS:
* Tartu University organizing Social Impact Data Hack on Nov 10-12. It's pretty fully booked, but techies are surely still welcome. Data sets will be published soon.

Q&A: 
* Any people we know in Latvia/Lithuania? Maarja-Leena will help.

**Comment by infokujur** [comment]
Ülevaade anti ja sellele ei järgnenud tegevusi.
