### ISSUE TITLE
Open Issue Tracker

### ISSUE THREAD

**Issue by tanelmallo** [okestonia/esindus#28]
#22 

* 87 issues, covering a lot of topics from organic farming, bee keeping to traffic and educational data. We collected demand, not supply. Around 80 datasets are available, and we have linked those to the issues. This is good, but also fragmented. Needs crowdsourcing to do something with it. We can call to the data owners an point the issues out.
* First year to get things going but now to start with community building. Ongoing dialogues with Data Science community. We have discussed if we could join forces with them to collaborate in checking the issues.
* If anythings seems to be missing, let us know!

**Comment by infokujur** [comment]
Issue tracker grooming starts again on regular basis few times a month. Exact time/space tbc. Event will be announced here: https://github.com/okestonia/opendata-issue-tracker/issues/88
