### ISSUE TITLE
Open data policy call for bids

### ISSUE THREAD

**Issue by tanelmallo** [okestonia/esindus#29]
#22 

* Ministry is looking fora strategic partner for : 3 years and 166.000 EUR worth of activities. Deadline for submissions Nov 13.
* Activities expected: 
1) management of Open Data portal (costs included in the 166K)
2) doing communication around open data - popularising in blogs, articles, Facebook
3) running a working group for open data (created in 2010, but currently does not discuss open data).
4) a couple of international initiatives
5) a couple of events
6) varia to improve open data policy
So in a way fixed list, but on the other hand, the topics that will be discussed are open.

Q: we are going to try it out, because we will be able to do this! Anyone willing to contribute to writing, let us know! Most of all needed a tech person who has relation to Estonian IT managers.

**Comment by Hillehinsberg** [comment]
OK Estonia bid won the contract!  In 3 years, OK-EE will be implementing activities that were identified by government as priroties for the policy, incl maintaining and developing the state portal,  furthering community relations and facilitating demand for more datasets. For more updates, see the FB group.

**Comment by infokujur** [comment]
We already started activities regarding to Issue tracker. Other activities tbc. We will create space for action plan in this repo, so everybody could participate and we could use most to strengthen open data community.
See more about Issue tracker grooming here: https://github.com/okestonia/opendata-issue-tracker/issues/88

**Comment by infokujur** [comment]
#34

**Comment by infokujur** [comment]
Markeerime projekti tegevused lausega:
Projekt "Avaandmete kasutamise edendamine" viiakse ellu Majandus- ja Kommunikatsiooniministeeriumi tellimusel EL struktuuritoetuse toetusskeemist "Infoühiskonna teadlikkuse tõstmine", mida rahastab Euroopa Regionaalarengu Fond. Hanke tulemusel viib projekti tegevused läbi MTÜ Open Knowledge Estonia.

**Comment by infokujur** [comment]
First steps about building blog (common information field): https://github.com/okestonia/esindus/issues/37

**Comment by infokujur** [comment]
Also international reports/meetings have their issue: #36

**Comment by infokujur** [comment]
Project is up and running and communications mostly are and will be on Estonian Open Data portal. https://opendata.riik.ee/
