### ISSUE TITLE
Juhatuse koosolekute memod

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#3]
12.12.2016 memo siin.
Palun kommenteerige vajadusel. Teema arenedes palume luua uue _issue_.
https://docs.google.com/document/d/18U1X9XZQpuIiE3x69KhqDiBmj7pRSUOH_8xefCAhQ1c/edit

**Comment by boamaod** [comment]
Me võiks teha memode jaoks eraldi kataloogi ja kirjutada neid memosid pigem maksimaalse koosvõime nimel otse standardses Markdown-tekstivormingus (seal ülal servas on **Create new file**):

* https://github.com/okestonia/esindus/tree/master/koosolekud

**Comment by Hillehinsberg** [comment]
1212 memo on täiendatud 6.jaanuari  infoga (mis vahepeal toimunud, ja mis plaanid järgmisteks sammudeks)
