### ISSUE TITLE
E-citizens charter 

### ISSUE THREAD

**Issue by tanelmallo** [okestonia/esindus#30]
#22 

The charter has two main goals:
1) that citizens know about their rights
2) that government agencies also know what they have to know (requirements for gov agencies)

There's a European layer to it.
We also visited AKI with Epp Maaten (one of the charter authors), and suggested introducing also the MyData principles to the charter. This was new to them, because public institutions don't have to follow GDPR.

We should also include in the discussion various digital-issues related NGO-s in Estonia.

**Comment by boamaod** [comment]
NGOs like Internet Society Estonia, Wikimedia Estonia, Estonian Free and Open-Source Software Association etc would probably have something to say on this charter but probably don't find enough initiative by themselves. I'd suggest going to them and organizing together a discussion on this charter.

**Comment by infokujur** [comment]
@boamaod Could You tag those organizations to this thread?

**Comment by infokujur** [comment]
#18 Summary here
