### ISSUE TITLE
Data journalism

### ISSUE THREAD

**Issue by tanelmallo** [okestonia/esindus#31]
#22 

Teaching data and knowledge for non-techies.
Needs suggestions for funding.
Tartu University media/communication people are preparing a data science MOOC (Märt Põder is building this), and they should be interested in data journalism.

We should also communicate with Taivo Pungas and the rest of data scientists community to find common ground. But they are quite professionally devoted and don't take so much interest in social topics.

**Comment by infokujur** [comment]
I took reference to err out. We do not have official project submitted with them. But we have been talking with many people who are looking forward to participate next steps.

**Comment by infokujur** [comment]
#19 Topic still hot #34 but needs concrete actions.

**Comment by infokujur** [comment]
http://www.etag.ee/wp-content/uploads/2016/09/The-data-revolution_JStoneman.pdf

**Comment by infokujur** [comment]
Tegevus käivitus: https://github.com/okestonia/opendata-issue-tracker/issues/93

**Comment by infokujur** [comment]
@infokujur tegeleb ja teiste tegevusliinide puhul palun ka avage oma issue tegevusliini kohta. @boamaod - Kas UT MOOC kohta on uudiseid? @infokujur suhtleb andmeteadlastega küll, kuid hetkel veel avaandme projekti käigus peamiselt, kuid jutuks tuleb ka andmeajakirjandus.
