### ISSUE TITLE
Litsentseerimise teema läbi arutada - kohustus puudub ja seetõttu jäetakse see samm astumata

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#33]
Selle teemale on raamistik olemas Avaandmete rohelises raamatus:
https://opendata.riik.ee/et/roheline-raamat

 4.4 	Andmehulga litsents
Ilma sõnaselge andmehulga litsentsita ei tea kasutaja, mida ta andmetega/metaandmetega teha võib. Õiguslikult eeldatakse, et kasutaja ei tohi ühelgi erijuhul mitte midagi teha, enne kui ta pole ühendust võtnud andmete omanikuga. Kuigi avaliku sektori teabe direktiiv ja praegune AvTS seadus ei kohusta otseselt litsentsi kasutamist, on soovituslik anda litsents parema piiriülese koosvõime saavutamiseks. Litsents
•	ütleb kasutajale ja taaskasutajale, mida too võib teha teabevaldaja andmete ja metaandmetega;
•	julgustab andmete/metaandmete kasutamist ja taaskasutamist teabevaldaja soovide kohaselt;
•	tähendab nõuet viidata autorile, tänu millele levib teadmine teabevaldaja tegevuse tulemustest.

Avaliku sektori teabe direktiivi muudatuse  preambuli punkt 26 selgitab litsentseerimise põhimõtteid järgmiselt: „Avaliku sektori teabe taaskasutamise litsentsidega tuleks igal juhul kehtestada taaskasutamisele võimalikult vähe piiranguid, piirdudes eelistatavalt allikale viitamisega. Siin peaks olema oluline roll ka veebis kätte saadavatel avatud litsentsidel, mis annavad suuremad taaskasutamise õigused ilma tehnoloogiliste, rahaliste ja geograafiliste piiranguteta ning põhinevad avatud andmeformaatidel“. Avaliku sektori teabe direktiiv ei kohusta otseselt liikmesriike taaskasutuse juures litsentse kasutama. Direktiiv annab reeglid, mida tuleb siis rakendada, kui litsentse kasutatakse. Euroopa Komisjonis on koostamisel soovitused litsentside valikuks ja kasutamiseks. Kõne all on ka üleeuroopaliste litsentside väljatöötamine.

**Comment by infokujur** [comment]
Issue tracker'il märgime selle teemaga seonduvad issued _license_ märkega.

**Comment by infokujur** [comment]
Kaardistan materjali TLÜ ja TTÜ teadlastele etteantud juhend: http://htk.tlu.ee/xerte34/play.php?template_id=59

**Comment by puik** [comment]
Kultuuripärandi kontekstis haakub asjaga [**Rightsstatements**](https://rightsstatements.org) autoriõigusliku seisundi deklaratsioonide nimistu, mille eesti keelde tõlkimise protsess on pooleli (vt ka [kommentaari teises lõimes](https://github.com/okestonia/opendata-issue-tracker/issues/29#issuecomment-366991509)).

**Comment by tkardi** [comment]
Hetkel peast ei mäleta, kuid kas rohelises raamatus mitte (tungivalt) ei soovitatud Creative Commonsi litsentsipere kasutamist?

**Comment by boamaod** [comment]
@tkardi, jah, soovitati küll. Litsentsiprobleem pole väga terav avaandmetega seoses (vist eelkõige, kuna neid on veel nii vähe ja korralikult avaldatud avaandmed Eestis on enamasti vähemalt püütud CC litsentsiga avaldada) -- peamine probleem andmetega, mis on avaldatud lihtsalt kuskil asutuse lehel, sj dokumendiregistris vm eri eesmärkidega registrites, nt majanduslike huvide deklaratsioonide register tekitas mul viimati selle küsimuse -- kuna litsentsi polnud, siis kaasamine rahvusvahelistesse korruptsiooniseire baasidesse oli võimatu.

**Comment by infokujur** [comment]
Litsentsi probleem on terav, kuna puudub ühtne arusaam. Kõigil on mingi isiklik kogemus ja idee, mille pealt üldistatakse. Teravamaks veel teeb see see, et on märkimata ja nii ei sünni tõsiselt võetavad rakendused. Keegi ei hakka suuremat süsteemi ehitama, kui juriidika pole paigas.

**Comment by tkardi** [comment]
Nõustun @infokujur'iga siin: litsentseerimine tuleks paika saada enne andmehulkade avaldamist, sest hiljem sellesse muudatuste tegemine võib olla päris keeruline. 

Tulistan nüüd puusalt, aga minu mulje on, et tegelikult pole juristid riigi- ja KOV asutustes paljudel juhtudel eelnevalt andmete litsentseerimisküsimustega/autoriõiguste temaatikaga sügavamalt kokku puutunud, sest nende asutuste juriidika fookus on mujal - hanked, seadusloome, maaomandi küsimused ja kinnisvara jms. Muidugi välja arvatud juhul kui asutus on spetsiifiliselt tegelenudki andmete müügiga. See ei ole mõeldud sugugi etteheitena, vaid lihtsalt olukorra konstanteerimisena - tegeletakse ju (ükskõik mis alal) süvitsi sellega, millele on "sotsiaalne tellimus". Seega võiks igasugune abi, mis aitaks lahti seletada avaandmete litsentseerimise vajadust ja konkreetsete PL litsentside tähendust, olla vägagi teretulnud. Alustades sellest, et kui andmehulgal pole kaasas avatud litsentsi, siis tegelikult pole tegu avatud andmetega. Isegi kui need on ilma tehniliste piiranguteta kuskilt dokumendiregistrist või veebilehelt või FTPst allalaetavad.

Ning lihtsalt uitmõttena - võib-olla peaks AvTS otseselt sõnastama, et kui avaliku sektori andmed ise on "vaikimisi avatud", siis need on vaikimisi avatud nt `public domain` (CC0) alusel, välja arvatud juhul kui andmehulga juures on sätestatud teisiti? Oleks see seadusloome mõttes üldse võimalik/lubatud?

**Comment by infokujur** [comment]
Avaandmete töögrupp on sellega tegelenud ja sisendit korjamas infopäevalt 27.09.2018.
Tegeleb edasi, kuna teema on oluline.
https://github.com/okestonia/opendata-issue-tracker/issues/95

**Comment by infokujur** [comment]
Portaalis opendata.riik.ee läheb default CC3.0 juurde, kui tõlgitud saab cc 4.0, siis see.
