### ISSUE TITLE
International open data surveys

### ISSUE THREAD

**Issue by maarjatoots** [okestonia/esindus#36]
Tere!

Mina olen Maarja ja olen OK-EEle järgmisel kolmel aastal abiks Eesti kohta info koondamisel rahvusvaheliste avaandmete võrdlusraportite tarbeks ([OECD OURdata survey](http://www.oecd.org/gov/digital-government/open-government-data.htm), [European Data Portal](https://www.europeandataportal.eu/sites/default/files/edp_landscaping_insight_report_n2_2016.pdf), [Open Data Barometer](http://opendatabarometer.org/?_year=2016&indicator=ODB) & [OKFNi Open Data index](http://global.survey.okfn.org/). Kui ma parasjagu sellega ei tegele, toimetan TTÜ [Nurkse instituudis](https://ttu.ee/nurkse) doktorandi-nooremteadurina ja uurin avaliku sektori IT-innovatsiooni barjääre.

Selle issue alla koondub edaspidi kogu info nimetatud uuringute teemal, vajadusel saab siin ka küsimusi tõstatada ja sisendit koguda. Esimesena on juba õige pea päevakorral OECD uuring, mille küsimused loodame asap kätte saada ja hoogsalt tööd alustada. Püsige liinil!

***

Hi all,

I am Maarja and will assist OK-EE in collecting and reporting information about Estonia for international open data surveys/rankings in the next three years, incl. [OECD OURdata survey](http://www.oecd.org/gov/digital-government/open-government-data.htm), [European Data Portal](https://www.europeandataportal.eu/sites/default/files/edp_landscaping_insight_report_n2_2016.pdf), [Open Data Barometer](http://opendatabarometer.org/?_year=2016&indicator=ODB) & [OKFN Open Data index](http://global.survey.okfn.org/). Other than that, I’m working as a junior researcher and doing  my PhD on the barriers to public sector IT innovation at the TTU [Nurkse Institute](https://ttu.ee/nurkse).

All information about these surveys will be assembled under this issue, which can also be used to discuss specific questions and gather input if need be. The first item on the agenda will be the OECD survey for which we are hoping to get the questions asap. Stay tuned!

**Comment by infokujur** [comment]
Oleme seda @maarjatoots arutanud ning avaldame selle info edaspidi opendata.riik.ee Uudiste rubriigis.
All related info will be published https://opendata.riik.ee/
