### ISSUE TITLE
Data journalism on opendata.riik.ee blog

### ISSUE THREAD

**Issue by annegretepeek** [okestonia/esindus#37]
Tere!

Mina olen Annegrete. Taustalt olen statistik/andmeteadlane ja töötan Tartu Ülikooli [CITISe tiimis](http://citis.ut.ee/). Järgmisel kolmel aastal aitan OKEEl väärindada avaandmeid. Selleks küsin küsimusi, analüüsin andmeid ja kirjutan postitusi leitud tulemustest [siin](https://opendata.riik.ee/et/blog).

Siia issue alla koonduvad minu tegevused. Siin viitan nii analüüsidele kui ka postitustele. Sina saad siin anda soovitusi, tagasisidet ja pakkuda välja uusi teemasid. Küsime küsimusi! 

---

Hi!

I'm Annegrete. I'm a statistician/data scientist and work at University of Tartu in [CITIS team](http://citis.ut.ee/). In the next three years I will help OKEE to give more value to open data. I'll ask questions, analyze data and post about findings [here](https://opendata.riik.ee/en/blog).

Under this issue I will be posting about my activities. Here will be references to the analysis and the posts. You can also give recommendations, feedback and offer new subject. Let's ask questions!

**Comment by annegretepeek** [comment]
Praeguseks olen kirjutanud kaks postitust Avaandmete portaalis. Esimene postitus räägib [kiiruseületamistest](https://opendata.riik.ee/et/blog/kes-see-siin-kihutab) ja teine [basseinide vee kvaliteedist](https://opendata.riik.ee/et/blog/vesi-meie-basseinides). Taustamaterjalid asuvad kaustas [Data-Vis-Protos](https://github.com/okestonia/Data-Viz-Protos). Tagasiside on oodatud. 

---

I have written two blog post in Open Data Portal. First post talks about [speeding](https://opendata.riik.ee/en/blog/who-one-speeding-3) and second about [water quality in pools](https://opendata.riik.ee/en/blog/water-our-pools). The background materials are in [Data-Vis-Protos](https://github.com/okestonia/Data-Viz-Protos) repos. Feedback is welcome.

**Comment by infokujur** [comment]
All articles will be posted in News section: opendata.riik.ee Watch there!
