### ISSUE TITLE
OKEE juhatuse töökorralduse kokkulepe

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#38]

**Comment by infokujur** [comment]
#34

**Comment by tanelmallo** [comment]
NÄIDIS: Core Team Memorandum of Understanding MyData 2018 (kõik read ei pruugi meile kohalduda - vaatame läbi ja diliidime ära, mis pole vajalik?)

**Celebration:**
- I actively give thanks and acknowledge others.
- I take time to celebrate things done well by myself and others.

**Ownership:**
- I choose or agree to take on all my tasks. No one will assign me tasks without my consent.
- This is my project: I have the right to have my opinions and suggestions heard and taken into consideration, and I also have the right to be involved in major decisions regarding the project

**Leadership**:
- I have the right to clear explanation of what is expected of me and the duty to let others know what I need from them.
- I am the lead for my  Area of Responsibility  and I have the right to make executive decisions  in that area.
- I respect the leadership of others.
- Consent over consensus  decision-making as default

**Responsibility:**
- I keep GCal updated on my scheduled absences of three days or more and respect others’ indicated time off.
- I can  send  Slack messages whenever and will  respond  within two working days (which does not mean “immediately”) =  response window .
- I respond to others’ ideas and questions in core chat.
- GCal terminology:
- Unavailable  = not reading Slack/email/etc, not working on anything
- Limited availability  = will respond to messages sporadically but within the  response window , not actively working on stuff.

**Openness:**
- I am open to ideas from all sources and consciously presume and see value in all contributions.
- I work and communicate as openly as possible while respecting others’ right to privacy and confidentiality.
- I involve the community and volunteers in my work as much as possible.

**Respectfulness:**
ShortURLhere:h  ttp://okf.fi/mou-mydata2018
 - I use only respectful language when dealing with my team members and others involved with the project. I avoid making jokes at others’ expense.
- I respect others’ stated boundaries and commit to stating my own.
- If I feel bad, I communicate that clearly and respectfully.

**Communication:**
- I build on what’s said before (“y es ”, “and”  ) and avoid ‘stop’ words that close off communication (“no”, “but”).
- I ask if something doesn’t make sense to me. I don’t assume everyone has the same context and priorities as me.
- I have the right and the duty to ask for help as well as to offer help.
- (Discovering the motive behind questions)
- (Responsible for making your needs clear: need input/celebrate with me/FYI)

**Accountability:**
- I make an effort to schedule my tasks realistically and inform others if/when things and schedules change.
- I am accountable to myself and my team members for my work and progress.
- I will update others when asked to do so, even if that update is “no progress”. I have the right to ask again if I don’t get an answer and a duty not to be offended if I am asked repeatedly.
- I am accountable to the team for my adherence to this code. I will listen if I am reminded about it and I have a duty to remind my teammates if I feel they have forgotten.

**Comment by tanelmallo** [comment]
The current board proposes to the next board to take a step forward with this agreement.

**Comment by tanelmallo** [comment]
Allpool arutamiseks juhatuse (ja iga konkreetse projekti) töökorralduslikud põhimõtted. Kogemuse põhjal loodan, et konkreetsus neis teemades võimaldab ühiseid plaane teha ja ellu viia, rõhuasetusega usaldusel, kommunikatsiooni tagamisel ja üksteisega arvestamisel. See ei vaja allkirjastamist, vaid arutelu, teadlikku kokkulepet ja järgimist.
1) Ma valin ise oma ülesanded (keegi ei määra mulle ülesandeid ilma minu nõusolekuta);
2) Ma vastan mulle suunatud küsimustele [mis kanalis?] kahe [kolme?] tööpäeva jooksul. Annan teada, kui olen pikemalt kättesaamatu [jagatud kalender?]
3) Ma kooskõlastan teiste juhatuse liikmetega seotud materjalide, info jmt jagamise kolmandate osapooltega, välja arvatud algusest saadik avalike materjalide puhul.
4) Ma planeerin oma tegevused realistlikult ning teavitan teisi kui asjaolud/ajakavad muutuvad.

**Comment by infokujur** [comment]
https://github.com/okestonia/esindus/issues/34
OKEE koosolek 21.11.2018

Kinnitasime, et
1. Ma valin ise oma ülesanded (keegi ei määra mulle ülesandeid ilma minu nõusolekuta) ja ma planeerin oma tegevused realistlikult ning teavitan teisi kui asjaolud/ajakavad muutuvad.
2. Ma vastan mulle suunatud küsimustele @okee.ee eposti aadressil kolme tööpäeva jooksul. Annan teada, kui olen pikemalt kättesaamatu automaatvastusega selle sama e-posti aadressil.
3. Ma kooskõlastan teiste juhatuse liikmetega seotud materjalide, info jmt jagamise kolmandate osapooltega, välja arvatud algusest saadik avalike materjalide puhul.
