### ISSUE TITLE
Kommunikatsioonikanalid

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#4]
**Github**
https://github.com/okestonia
Siia kujuneb tegevuskava ja selle tegevuste täitmisega soetud info sh juhatuse koosolekute memod.

**Slack**
https://okestonia.slack.com
Virtuaalne reaalajas suhtlemine.

**WWW**
Peamine info http://ee.okfn.org/. Avaandmetega seotu jagatakse ka läbi http://opendata.ee/.
http://ee.okfn.org/
http://opendata.ee/

**Facebook**
Peamine info okestonia peal. Avaandmetega seotu jagatakse ka läbi opendataestonia lehe.
https://www.facebook.com/okestonia
https://www.facebook.com/opendataestonia

**Twitter**
https://twitter.com/okestonia

**Comment by boamaod** [comment]
Meie ametlik veeb on muidu ju: http://ee.okfn.org/

**Comment by boamaod** [comment]
Twitter on: https://twitter.com/okestonia

Lisaks on meil vaja saata liikmetele e-maile, mis tähendab, et mingil kujul on vaja ka meililisti. Kas meil on vaja ka mingit foorumit vmt avaliku arutelu kanalit? Ilmselgelt ei hakka paljud meie liikmed kunagi midagi arutab Facebookis või Twitteris (kõigil pole neid kontosid ja paljud ei taha seda lihtsalt teha). OK rahvusvaheline kontor peab üleval foorumit, kus [saaksime endale reserveerida ühe jaotise](https://discuss.okfn.org/c/local-groups/), aga kui me seda reaalselt ei kasuta, siis oleks see üleliigne ja ka tühi kanal on infomüra. Võimalik, et meile piisab, kui arutelude meedium lepitakse kokku iga projekti jaoks eraldi ja GitHubi kommentaariumid peaks olema samuti piisavalt lihtsalt kasutatavad (ja nende pluss on neutraalsus (pole FB/Twitter) ja paiknemine samas kohas meie tegevuste/projektide/koodi haldusega, sellel on plusse kaasamise aspektist (keegi võib avastada soovi mõne projekti juures kaasa lüüa, millest ta mõnes teises foorumis/keskkonnas kuidagi teada ei saakski).

**Comment by boamaod** [comment]
Juttu on olnud ka mingi regulaarsusega raadiosaate/podcasti tegemisest. Küsimus oli, et kellega koos seda teha ja mina lubasin uurida. Kadi Mariaga oli sellest veidi juttu, aga ma pole praegu rohkem tegelenud.

**Comment by boamaod** [comment]
Meil võib olla vaja ka liikemete chatti, see võib ilmselt olla ka projektipõhine, aga tekivad ka chattide sildamise küsimused (projektide vahel ja projekti raames), et keegi ei jääks soovitud infovoost kõrvale.

**Comment by tormi** [comment]
Kui chatijutud põhiliselt avalikud, siis soovitaks rakendust https://gitter.im/, mis on GitHubiga integreeritud.

**Comment by Hillehinsberg** [comment]
Should we have a regular  (monthly) mailing to the member list?
- the aim is to keep interested members and others up-to-date  with most issues in one channel.

**Comment by boamaod** [comment]
We will be having regular meeting to discuss/get stuff done etc at Astra building Tallinn Uni 428 every Thursday from 16. People can join over Internet.

**Comment by infokujur** [comment]
#11 Sure we need to get barriers down as possible. Any volunteers setting things up?

**Comment by tormi** [comment]
One can easily deploy Slackin to Heroku, see:
- https://github.com/rauchg/slackin#usage (Heroku link)
- https://medium.com/@abhaytalreja/slackin-slack-signup-button-for-free-7126e35d4956#.igkudvssu

**Comment by tormi** [comment]
#11 is really easy to set up, but needs some credentials:
![heroku](https://cloud.githubusercontent.com/assets/146800/24002975/d0093f5c-0a6a-11e7-98c5-df451dd00fa6.png)

**Comment by infokujur** [comment]
Suunasin esinduse ja issue trackeri slacki, teisi kanaleid ei julge avada, sest ma ise seal ei ole kohal. Kui keegi on kohal ja suhtleb, siis saab järjest ühendatud ruumi edasi ehitada.

#17 Juhatuse koosolekul arutasime, et sellest sügisest hakkame korraldama momentume korra kuus. Seni olid G48 ja Mydata organiseerimise tõttu nad korra nädalas. Kui tuleb uuesti mõni suurüritus, siis saab vajadusel tihendada.

Uudiskirja ka toome suvepuhkuselt tagasi. Eesmärk täna-homme välja saata.

**Comment by infokujur** [comment]
Sulgen selle teema praegu sellisena. Kui vaja konkreetse kanaliga tööd teha, siis palun avage uus konkreetne teema.
