### ISSUE TITLE
Vaja avaandmete kataloogi musternäidet teistele viitamiseks

### ISSUE THREAD

**Issue by boamaod** [okestonia/esindus#41]
Oleks vaja lihast-luust näidet sellest avaandmete kataloogist, mida võiks teistele eeskujuks tuua. Mis tingimused peaks olema täidetud ja mis võiks olla kriteeriumid? Loomulikult on kriteeriumid [avaldamisjuhises](https://www.ria.ee/public/Arhitektuur/Avaandmete_loomise_juhend.pdf) ja [rohelises raamatus](https://opendata.riik.ee/et/roheline-raamat) välja toodud, aga oleks vaja just näidata, kes on seda reaalselt nii hästi teinud, et seda võiks teistele eeskujuks tuua stiilis "mine ja vaata seda kataloogi"...

Minu jaoks peamised kriteeriumid, mida rõhutada (mh osaliselt välja toodud #23 all):

* On olemas andmete üldkirjeldus ja avaldamise põhimõtted;
* Andmed on avaldatud struktureeritud ja/või taaskasutataval kujul (lihtsaimal kujul andmete URLi püsivus, eri ajal avaldatud andmehulkade või nende ühemõtteline seisu leitavus URLi järgi ja/või peenem tehniline lahendus JSON vmt formaadis, kus struktuuur/taaskasutatavus on tagatud formaadiga);
* Andmete/andmehulga juurde on ühemõtteliselt märgitud litsents;
* Andmehulga juures on kirjeldatud andmete struktuur (vajadusel selle versioon), uuendamise põhimõtted ja päritolu/tähendus asutuse infosüsteemides;
* On toodud ära viide opendata.riik.ee kirjele (see näitab ja sunnib asutust tagama, et info seal on värske);
* On üleskutse andmeid kasutada (kui on toodud viide näidetele, kuidas juba on kasutatud, siis seda parem) ja relevantne kontakt lisainfo saamiseks (näitab, et kataloog pole niisama vormitäiteks tehtud, vaid asutus võtab avaandmeid tõsiselt).

Mis veel? Mis asutus(t)e kataloog(id) võiks olla parima praktika musternäiteks?

**Comment by boamaod** [comment]
Lisada võiks vist:

* Avaandmete kataloog on lihtsasti leitav asutuse kodulehelt ja kataloogi aadress vastab andmete avaldamise rohelises raamatus nõutud URLi standardile `www.domeen.ee/[et]avaandmed` või on avaldamise juhendist lähtuvalt muul viisil "kõigile soovijatele lihtsalt leitav".

Teen otsa lahti KOVidega:

# Pärnu

Avaandmete kataloog pole linna kodulehelt leitav, kuid on pedus dokumendiregistri lehel selle laienduse kujul:

* https://edok.parnu.ee/public/index.aspx?o=924&o2=924&u=-1&hdr=od&tbs=all

Andmed on ära toodud [As is](https://en.wikipedia.org/wiki/As_is) põhimõttel, riigiportaali pole kantud, litsentse pole, juhendeid pole -- positiivne on masinloetav ja taaskasutamist võimaldav formaat, mis siiski pole eriti kasulik, sest andmete struktuuri ja uuenemise kohta tuleb kõik ise välja mõtelda. Toodud on ära ainult linnavalitsuse üldkontakt.

Positiivne: JSON on hea formaat, sisuliselt võivad andmed olla ägedad ja kasutatavad.

# Tallinn

Andmed on koduehelt lihtsalt leitavad ja URL on ootuspärane:

* http://avaandmed.tallinn.ee/

Andmed on avaldatud koos elementaarsete kirjeldustega, iga andmehulk on eraldi kirjeldatud, kuigi puudub andmete ajalugu ja selge märkus uuendamise intervalli kohta, ka on kirjeldamata andmete struktuur, päritolu kohta on info samas kohati olemas. Andmetel puudub litsentsimärgis ja lehekülje allservas olev "Kõik õigused kaitstud © 2018 Tallinn" osutab, et andmete kasutamine pole ilma luba küsimata lubatud. Andmed ise tunduvad olevat mõistlikus formaadis, masinloetav, seal kus võimalik ja mitte, kus mitte, andmetele on peamine etteheide andmehulkade ajaloo puudumine (see võib samas olla osaliselt olemas XML struktuuris vmt, aga kuna see pole dokumenteeritud, siis on ajaloolise vaate olemasolu ebaselge).

Tallinna avaandmed on [kantud riigiportaali](https://opendata.riik.ee/en/dataset/tallinna-andmekogud), aga ainult üldkirjena, mis ei vasta portaali kasutusjuhistes seatud nõudele, et portaali peab olema kantud iga andmehulk eraldi. Ka puudub andmetel litsentsimärge ka riigiportaalis. Link riigiportaalile avaandmete kataloogis puudub.

Avaandmete kataloogi juures puudu kontaktinfo või muud juhised andmete kasutamiseks, ka pole toodud ära andmete avaldamise üldpõhimõtteid.

Positiivne: Eesti esimene ja kõige põhjalikum avaandmete kataloog KOVide seas, oleks litsentsid, andmete ajalugu ja kontaktinfo ka olemas, siis oleks KOVidest konkurentsitult esimene. Ka vajaks andmed korrektset esitamist riigiportaalis.

# Tartu

Linna avaandmete kataloog on rohelise raamatu nõuetele vastava URLi alt leitav ning leitav ka linna kodlehelt:

* http://tartu.ee/et/avaandmed

Andmetel on olemas litsents, kuigi seda pole iga andmehulga juures eraldi välja toodud, andmehulkadel on olemas elementaarsed kirjeldused ja märgitud on ka uuendamise intervall, kuid puudub andmehulkade struktuuri kirjeldus ning ajalooline vaade andmetest (see võib siiski olla peidetud mõne JSON vmt andmehulga struktuuri). Kuigi avaandmete kataloogil on üldosa, siis see ei kirjelda Tartu linna andmete avaldamise põhimõtteid, vaid kopeerib riigiportaali avalehte. Ka puudub avaandmete kataloogi juures kontaktinfo neile, kes sooviks andmete kohta lisainfot, lehekülje allservas on linnavalitsuse üldkontakt.

Andmete kataloogi kohta on [kirje riigiportaalis](https://opendata.riik.ee/en/dataset/tartu-linna-avaandmed), kuid see ei vasta portaali kasutamise nõuetele ega kirjelda iga andmehulka eraldi. Ka on riigiportaalis toodud ära teine litsents kui linna koduhelel (CC BY vs CC BY-SA). Link riigiportaalile avaandmete kataloogis puudub.

Positiivne: Tartul on kvaliteetsed andmed olemas, ka on kataloogi loomisel 2016. aastal põhiasjadele mõteldud (sj litsentsidele), kuid avaandmetega tegelemine on jäänud poolele teele, vaja oleks kontaktinfot ja andmete avaldamise põhimõtete kirjeldamist, ajalooline vaade oleks vaja lisada ning andmehulkade struktuurid vajaks kasutamiseks täsemat lahtikirjutamist. Loomulikult tuleks korrigeerida andmete esitus riigiportaalis.

**Comment by boamaod** [comment]
# Politsei- ja Piirivalveamet

Andmed leitavad mõningate komplikatsioonidega PPA kodulehelt (kodulehe otsing läbi Google'i ja kataloogi aadress ei vasta ühelegi standardile):

* https://www2.politsei.ee/et/organisatsioon/analuus-ja-statistika/avaandmed.dot

Andmete avaldamise põhimõtete kirjeldus on eeskujulik, sj on kirjeldatud andmete päritolu ning uuendamise intervall. Andmetel puudub kataloogis standardne litsents, kuigi lisatud seletuskirjas on öeldud, et andmeid "võivad kõik vabalt ja avalikult kasutada" -- sellest kahjuks ei piisa reaalseks kasutamiseks tarkvaraprojektides. Andmete struktuur ja uuendamine on kirjeldatud väga hästi, aga see võiks olla iga andmehulga kohta eraldi, samamoodi on küll kirjas andmete uuendamise intervall, kuid puuduvad ajaloolised andmed (võib väita, et see pole kumuleeruvate andmete puhul hädavajalik, aga siiski). Anmete formaat ja avaldamise viis on mõistlikud ning võimaldavad andmeid taaskasutada.

Kataloogi kirjelduses on toodud spetsiaalne kontaktaadress, kust saab lisainfot. Riigiportaalis [on andmed kirjeldatud korrektselt iga andmehulk eraldi](https://opendata.riik.ee/data/search?publisher=politsei--ja-piirivalveamet), seal on ka toodud litsentsiks CC BY (mis peaks olema toodud ka PPA lehel). Andmete kirjeldused portaalis pole päris täielikud, nt uuendamise intervall, ajaline ulatus jmt tunduvad ebaühtlased või suvalised. Huvitaval kombel on riigiportaalis rohkem andmeid kui PPA enda avaandmete kataloogis -- iseenesest positiivne, et andmeid on oodatust rohkem, aga see tekitab samas ka segadust.

Positiivne: andmed on põhjalikud ja andmete struktuuri kirjeldus teeb need reaalselt kasutatavaks, ka korraldas PPA oma andmete tutvustusürituse ning avaadmete jaoks on asutuses määratud konkreetne vastutaja -- see koos korrektsete kirjeldustega riigiportaalis julgustab andmete potentsiaalseteid kasutajaid andmeid uurima ja nendega tegelema (vt nt [Renee Trisbergi FB lehelt](https://www.facebook.com/photo.php?fbid=10212754893661555&set=a.1196923777604.30078.1663782060&type=3&theater) või [Annegrete blogipostitust riigiportaali blogis](https://opendata.riik.ee/en/node/27)).

**Comment by boamaod** [comment]
# Justiitsministeerium

Andmed on leitavad kodulehe otsingu kaudu, sh rohelises raamatus nõutud aadressilt, küll edasisuunamisega, aga siiski:

* https://www.just.ee/et/avaandmed => http://www.rik.ee/et/avaandmed

Andmetel puudub avaldamise põhimõtete üldkirjeldus, aga on korrektselt määratud litsents (võiks olla iga andmehulga juures selgelt välja toodud, sj viitavad mõned andmehulgad edasi alamlehtedele, kus litsentsi siiski ära toodud pole ja pole selge, kas ja mis litsents seal siis ikkagi kehtib), puuduvad koondatult üksikute andmehulkade struktuuri kirjeldused, küll on olemas avaldamise intervall ja märkus formaadi kohta. Erinevalt paljudest teistest kataloogidest on mõnedel andmehulkadel ära toodud ka andmete ajalugu (nt [patendiameti andmed](http://avaandmed.rik.ee/andmed/PA/).

Riigiportaalis on toodud üheksast kataloogis olevast andmehulgast viis, kohati on kirjetes puudu nt andmete ajaline ulatus jm väljad. Litsentsimärgised ühtivad asutuse enda kataloogis tooduga ja asutuse enda kataloogis on link riigiportaalile (aga võiks olla ehk [teabevaldaja enda lehele riigiportaalis](https://opendata.riik.ee/en/publisher/justiitsministeerium)).

Puudub kontaktisik andmete kohta lisainfo saamiseks.

Positiivne: vähemalt osa puhul andmetest on olemas ajalooline vaade ning on toodud link riigi avaandmete portaalile.

**Comment by boamaod** [comment]
Panin siin pakutud kriteeriumid kokkuvõtlikult kirja #42 alla, sj koostasin siintoodud näidete alusel tabeli homse esitluse jaoks.

**Comment by tanelmallo** [comment]
Need on head olemasolevad näited kaardistuse alustuseks. Samas on Eestis üldisemad avaandmetega seotud praktikad välja kujunemata. Mh OKEE ja MKM ühistegevuse käigus kujunev ökosüsteem kujundab tegevuspõhimõtted ja parimad praktikad (sh standardites kokku leppimise kaudu), mille alusel on võimalik koostada ka dokumentatsioon/juhendmaterjalid (sh kataloogi musternäited).

**Comment by boamaod** [comment]
Teema vahekokkuvõtteks [Tallinna koosoleku jaoks koostatud slaidid](https://docs.google.com/presentation/d/1pVqrDtMNxqA0uelbkNNOBQ0MFGbqDNhVA7f0DNUg-Mk) (18.04.2018).

**Comment by infokujur** [comment]
@boamaod , kas Sa tegeled sellega või paneme selle tegevusliini praeguseks kinni?

**Comment by infokujur** [comment]
Tegevusi ja tegijat ei ole. Kuni aktiveerumiseni arhiveeritud.
