### ISSUE TITLE
Avaandmete kataloogide hindamise kriteeriumid versioon 0.1

### ISSUE THREAD

**Issue by boamaod** [okestonia/esindus#42]
# Üldkirjeldus, avaldamise põhimõtted, kasutusjuhis

Andmete üldkirjeldus on vajalik, et mõista asutuse andmekogude konteksti, see loob silla asutuse andmete ja nende taaskasutamise vahele kolmandate osapoolte poolt, ka saab üldkirjelduse ja andmete kasutamise juhisega tagada kasutamise kvaliteeti ning vältida möödarääkimisi ja juhuslikke väärkasutusi. Lisaks sellele annab andmekogude kirjeldus ja nende avaldamise teekaart ideid andmete avamiseks ja kasutamiseks tulevikus ning aitab leida koostööpartnereid teiste asutuste, ettevõtete, teadusasutuste jt andmekasutuse huvigruppide seast.

# Andmete olemasolu, leitavus ja formaat

Andmehulkade olemasolu on baaskriteerium, kuid nende hulk nõuab kvalitatiivset hinnangut, st arv on ainult hägus mõõdik, sest andmehulkade arvu saab kunstlikult tõsta pakkudes eri vaateid samadele andmetele. Andmete leitavus on oluline kriteerium, juhendite soovitatud standard-URL on http://www.asutus.ee/[et/]avaandmed ja asutuse kodulehelt peaks olema kataloog lihtsalt leitav. Andmete formaadile rakenduvad viie tärni kriteeriumid, mis ei tähenda, et olemasolevaid andmeid ei tohiks avaldada madalama kvaliteediga, kuid juba andmekogude loomisel peaks arvestama vajadusega avaandmete kataloogis avaldada vähemalt kolme tärni nõuetele vastavas formaadis, struktureeritult ja kooskõlas litsentsinõuetega. Eesti asutuste andmed on valdavalt kahe ja kolme tärni vahepeal ning seda mitte ainult andmehulkade endi formaadi, vaid pigem just muude nõuete pooliku täitmise tõttu.

# Kajastatus riigi avaandmete portaalis

Riigi avaandmete portaalis opendata.riik.ee peaks olema kirjeldatud kõik avaldatud andmehulgad, mis tagab andmehulkade kirjelduse ühtsetel alustel masinloetavuse metaandmete kujul ning suurendab oluliselt andmete leitavust huuvigruppide jaoks. Viide asutuse kirjele riigiportaalis on andmete kasutajale kvaliteedimärk ja kui avaldatud andmehulgad on riigiportaalis piisava detailsusega ja korrektselt esitatud, sh on märgitud andmete kasutamise litsents, uuendamise intervall, andmete ajalugu, relevantsed märksõnad Eurovoc ontoloogias jmt, siis see teeb andmed ilma tõrgeteta kasutatavaks. Riigiportaalil on standardne JSON API, mille abil saab neid uuendusi automatiseerida ning CKAN tehnoloogial põhinevatest portaalidest saab andmed ka automaatselt uuenema panna.

# Andmehulga litsents, struktuur, uuendamine/ajalugu

Ilma üheselt mõistetava ja standardse litsentsita andmed on kasutatavad ainult isiklikuks otstarbeks ning andmeprojektide tulemusi ei saa avaldada või ettevõtluseks skaleerida, sj rahvusvaheline kasutus on õiguslikel põhjustel välistatud. Andmete päritolu ja andmehulga struktuuri kirjeldamine on vajalik, sest ainult andmetele peale vaadates ei ole alati aru saada, kust need tulevad, mismoodi neid kogutakse ja kuidas neid tõlgendada ning kasutada. Kui andmeid avalikustada, siis on mõistlik juba säilitada ka nende ajalugu, sest see annab analüüsiks lisadimensiooni ning muudab läbipaistvaks nt muutused andmestruktuuris, sj ei pea avaandmete kataloogis esitamine olema takistuseks andmekogude ümberprojekteerimisel, sest andmestruktuure võib nende muutumisel versioneerida. Andmehulkade puhul on elementaarne tuua ära nende ajaline ulatus ning uuendamise intervall.

# Vastutav kontaktisik, kogukonnahaldus ja kasutatavus

Kui andmed on esmastele nõuetele vastavalt avaldatud ja nende vastu tuntakse huvi, siis tõsisemal kasutamisel tekib enamasti ikkagi küsimusi. Kui küsimused lähevad asutuse üldkontaktile, siis asutuse siseselt tähendab see, et avaandmete kogemus võib jääda asutuses laialepillutatuks ega kumuleeru, kasutaja peab aga küsimuse vastust potentsiaalselt mitme inimese vahel põrgatama ja korduvalt tausta seletama. Seetõttu on oluline, et asutuses oleks inimene, kelle ülesanne oleks huviliste kogukonnaga suhelda ning nende tagasisidet koguda. Nii on ka asutusel ülevaade, kus nende andmeid kasutatakse, mis on tekkivad küsimused ja kuidas avaandmete kataloogi kogukonna huvisid silmas pidades edasi arendada. Andmete tegelik kasutamine on ka avaandmete kataloogi edukuse mõõtmisel oluline mõõdik ning seda peaks asutus maksimaalselt soodustama, ka võiks andmete avaldamise eest vastutaja pidada silmas kogukonna enda kanaleid, nt https://github.com/okestonia/opendata-issue-tracker on hetkel koht, kus Open Knowledge juba rohkem kui aasta jooksul on kogukonna andmevajadusi kogunud ja kureerinud.

**Comment by tanelmallo** [comment]
Ettepanek uuele juhatusele: on vaja läbi mõelda, kuidas OKEE sarnaseid teemasid arutab ning oma ettepanekuid teeb ja haldab.
#51

**Comment by infokujur** [comment]
Tegevusi ja tegijat ei ole. Kuni aktiveerumiseni arhiveeritud.
