### ISSUE TITLE
Ühine kalender?

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#43]
Kõik üritused, timeslotid jms
Pakun omalt poolt demokraatialabor@gmail.com kalendrit.

**Comment by infokujur** [comment]
#34

**Comment by tanelmallo** [comment]
Jah, kasutame seni, kui sisemiste admintegevuste hulk on väike - seejärel teeme oma kalendri. Kes soovib OKEE tegevustel kalendris silma peal hoida, lisage demokraatialabor@gmail.com.
