### ISSUE TITLE
Uudiseid uudiskirja 2019

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#45]
OKI uudiskirja numbrid: https://us9.campaign-archive.com/home/?u=73f922f8e68e21a10efa21f02&id=32d370a7fc

**Comment by infokujur** [comment]
Juuni uudiskirja draft: https://drive.google.com/file/d/1QopiMfP3wHiOgmxT_lZUld5VuDjSG_H0/view

**Comment by tanelmallo** [comment]
The current board proposes to the next board to decide how often the newsletter goes out (e.g every 2 or 3 months) in the broader framework of communication plan.

**Comment by infokujur** [comment]
Otsus: kvartaalne uudisikiri.
Tanel tegeleb järgneva aasta jooksul.

**Comment by infokujur** [comment]
Jaanuari uudiskirja põhi: https://docs.google.com/document/d/1azY1dYMllHsacrLqEv9-UFdHp8lpilzh_GHEaMVClV8/edit

**Comment by infokujur** [comment]
Tegevusi ja tegijat ei ole. Kuni aktiveerumiseni arhiveeritud.
