### ISSUE TITLE
Juhatuse koosolek 06.06.2018

### ISSUE THREAD

**Issue by tanelmallo** [okestonia/esindus#46]
Kuna 14. juuniks on üldkoosolek osaliselt (Githubis) välja kuulutatud, aga formaalne kutse 2 nädalat enne koosoleku toimumist välja kuulutamata, ent majandusaasta aruanna vajab kinnitamist juuni jooksul, otsustasime toimida järgmiselt
(1) teatame et üldkoosolek toimub digitaalselt ning edastame samas digidoc.ee kaudu allkirjastamiseks protokolli, mille lisa on majandusaasta aruanne: https://docs.google.com/document/d/17I8JX5QdOeB6aQgbIoL2QVWcNeMPhAW7cM0potFISmk/edit#
(2) lisame selle protokolli Githubi issueks neile, kes soovivad kommenteerida/küsida ning jätame selleks ajavahemiku teate saamisest kuni 27.06.2018 kell 23:59;
(3) doodledame juhatuses: füüsiline üldkoosolek augusti lõpus (sealt viia infopäevale info) või infopäevaga samal päeval lõpus 1h.

**Comment by infokujur** [comment]
(1)(2) https://github.com/okestonia/esindus/issues/47

(3) Doodeldamise tulemus Üldkoosolek 24.08 kell 17:00-18:00 https://github.com/okestonia/esindus/issues/49
