### ISSUE TITLE
Open Knowledge Estonia 2018. a üldkoosoleku protokoll

### ISSUE THREAD

**Issue by tanelmallo** [okestonia/esindus#47]
**OPEN KNOWLEDGE ESTONIA 2018. A. ÜLDKOOSOLEKU PROTOKOLL**

**Aeg ja koht**
Üldkoosolek toimub digitaalselt ajavahemikus 11.-27. juuni 2018, koosolekut juhatatakse Tallinnast.

**Osavõtjad**
Üldkoosolekust osavõtnuteks loetakse käesoleva protokolli allkirjastanud liikmed. Tulenevalt Open Knowledge Estonia põhikirjast on üldkoosolek otsustusvõimeline sõltumata osalejate arvust.

**Juhataja**
Digitaalse üldkoosoleku toimumise eest vastutab juhatuse liige Maarja-Leena Saar.

**Päevakord**
Open Knowledge Estonia majandusaasta aruande kinnitamine.

Kinnitame majandusaasta aruande liikmete digiallkirjadega käesolevale protokollile digidoc.ee keskkonnas (allkirjastamiskutsed edastatud liikmete e-maili aadressitele digidoc.ee keskkonna kaudu).
Majandusaasta aruannet puudutavad kommentaarid ja küsimused juhatusele Github keskkonnas kuni 23:59 27.06.2018.
Majandusaasta aruande allkirjastamine on avatud kuni üldkoosoleku lõpuni 27.06.2018 kell 23:59.

**Lisa 1:** Open Knowledge Estonia majandusaasta aruanne
[OKEE 2018 majandusaasta aruanne.pdf](https://github.com/okestonia/esindus/files/2095271/OKEE.2018.majandusaasta.aruanne.pdf)
 (edastatud koos üldkoosoleku elektroonilise kutsega).
**Lisa 2:** Open Knowledge Estonia liikmete nimekiri seisuga 11.06.2018: https://github.com/okestonia/esindus/blob/master/members.md

**Comment by puik** [comment]
Majandusaasta aruandes on füüsilisest isikust liikmete arvuks seisuga 31.12.2017 kirjas *4 (neli)* – see on ju kindlasti vale number...

**Comment by infokujur** [comment]
See 4 on seotud osapooled ehk juhatuse liikemete arv. Samas aruandes on välja toodud ka kogu liikmete nimekiri https://github.com/okestonia/esindus/blob/master/members.md . Aga uurin veel üle, kas see loogika on hea.

**Comment by infokujur** [comment]
Esitatud 01.07.2018 12:09 ja vastu võetud. Kõik korras.

**Comment by infokujur** [comment]
@puik Ühingul on hetkel 15 ametlikku liiget ja 4 juhatuse liiget (nimekiri siin: https://github.com/okestonia/esindus/blob/master/members.md).
