### ISSUE TITLE
Üldkoosolek 24.08 kell 17:00-18:30

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#49]

**Comment by infokujur** [comment]
Küsimus, mida soovime üldkoosolekul näha?
Soovime potensiaalseid juhatuse liikmeid oma tegevussuunast rääkima ja tuua seda infpäeval töötoana tutvustama.
https://github.com/okestonia/esindus/issues/48

**Comment by infokujur** [comment]
Infopäeva teemade korje siin: https://github.com/okestonia/opendata-issue-tracker/issues/95

**Comment by infokujur** [comment]
Järgmise infokirjaga välja: https://github.com/okestonia/esindus/issues/45

**Comment by infokujur** [comment]
Esialgne registreerimisankeet:
https://docs.google.com/forms/d/e/1FAIpQLSfWs3rPW9UNaD1pxWWVXkf-aION788kyy3bXR3I88sI9Q8RGw/viewform

**Comment by infokujur** [comment]
Fb üritus siin: https://www.facebook.com/events/986772438150859/

**Comment by edmundlaugasson** [comment]
Teen ettepaneku võimaldada osaleda infoühiskonnale ja 21.sajandile kohaselt üle interneti. Näiteks Jitsi Meet pakub selleks väga lihtsat võimalust veebikeskkonna https://meet.jit.si/ näol. Seal saab määrata sobiva nime, mida võib ka kohe peale kaldkriipsu kirjutada ega pea esmalt sinna üldaadressile minema. Nime valimisel tuleks läbi mõelda, et võibolla soovitakse veel teisigi kanaleid luua ja seetõttu võiks olla mingi ühine nimetaja (nt okee) alguses ja seejärel siis nt yldkoosolek vms. Üldiselt sidekriipse ei soovita kasutada - pigem mängida tähesuurusega.
Tegemist veebinarikeskkonnaga, mille kasutamiseks piisab graafilisest veebilehitsejast ja nutiseadmetele on ka vastav rakendus olemas. Esimese kasutaja ühinemisega vastav kanal luuakse. Kanali looja saab määrata ka salasõna kui vaja peaks olema. Saab ka määrata, et kanaliga ühinejate mikrofonid summutatakse vaikimisi. See võiks ka olla nõue, et kui ei räägi vaid kuulatakse siis mikrofon peaks olema summutatud. Jitsi Meet ei piira osalejate arvu, minimaalne ühenduskiirus alla/üles oli minuteada 128 kbps. Üle interneti osalemisvõimalus annaks ilmselt suuremale hulgale inimestele võimaluse osaleda.

**Comment by tanelmallo** [comment]
Tänan, Edmund!
Üle veebi osalemise võimalus on loomulikult alati olemas. Peame oluliseks siiski ka füüsiliselt kokku saada, sest kohaletulek annab võimaluse füüsiliseks aktiivsuseks (jalgsi, rattaga), tõstab teadlikkust ühistranspordi kasutamise osas ning annab kohtumisele inimliku mõõtme.
Jitsi on tõhus, kuid et mitte nõuda osalejatelt ühe kohtumise jaoks (tõenäoliselt) uue rakenduse installi, tegin seekordseks kohtumiseks skype-kanali: (https://join.skype.com/bJFMTrF9ai9U). Kommunikeerime seda FB-s ja liikmetele otse.
Tervitades
Tanel

**Comment by edmundlaugasson** [comment]
Jitsi Meet just ei nõua millegi paigaldamist ega kasutaja tegemist kuna on veebipõhine ja valmis kohe kasutamiseks kuna mingit kasutajat ka ei ole vaja teha - lihtsalt etteantud URL avada, nagu võis minu eelmisest postitusest veenduda. Julgustan kasutama eesti keelt niipalju kui võimalik, inglisekeelsed parasiitlaenud ei tee meie emakeelele au. Muidugi on füüsiline aktiivsus oluline ja näiteks minu töökoht on veloergomeetri seljas nii kodus kui tööl. Kui oleksin teie juures siis peaksin tõepoolest istuma. Skype'i kanal ei ole sobiv, [sisaldab nuhkvara](https://www.youtube.com/watch?v=qc8i7C659FU) ei soovita seda kasutada. Kuigi jah - antud  kanali puhul ei oleks vahet kuna on ka veebipõhine. Kuid paraku teadaolevalt kõik, millele Microsoft käe külge paneb, ka ära rikutakse. Seetõttu on Skype'i kasutamine teadlike inimeste poolt välistatud. Äärmisel juhul kapseldatakse see eraldi virtualiseeritud kihti kui tõesti muud üle ei jää.

**Comment by tanelmallo** [comment]
Tänan selgituse ja lingi eest, Edmund! Olen ise varasemalt Jitsit kasutanud mobiililt, mis vajas rakenduse allalaadimist, ega teadnud et brauseris on kanali tegemine nii hõlbus! Kasutusmugavuse osas olen Jitsiga rohkem rahul kui Skypega. Kanali turvalisuse suhtes respekteerin, et erinevatel inimestel on erinev tundlikkus ja sellest tulenevad eelistused, ent isiklikult ma ei ole veel jõudnud vajaduseni selle osaga digitaalsest hügieenist süvenenult tegeleda. Ent selleteemalised tegevused laiemas mõttes võiksid muuhulgas OKEE võrgustikus toimuda. Vahetasin hiljuti kirja Martin Paljakuga, et ALVATALi tegemiste kohta rohkem teada saada, ning ta vastas, et organisatsioon on küllaltki passiivses olekus. Kas ka sina oled ALVATALiga seotud ja/või oleksid huvitatud jõudude ühendamisest?

**Comment by edmundlaugasson** [comment]
Vastasin e-kirjale. Jah, olen Alvataliga seoud küll.

**Comment by infokujur** [comment]
Arutasime korralduslikke küsimusi eile ja @edmundlaugasson idee tundus hea. Testisime tööriista ja proovime üldkoosolekul kasutada.

Jagame kanalites sõnumit:
Yes, its possible to participate also online. For that we use Jitsi https://meet.jit.si/okeeyldkoosolek
- No installation needed for desktop version. Mobile yes

Some tips how to handle many participants through online meeting:

- If You tune in - type in Your name - so we know who we are talking with
- mute Your microphone
- ask questions through chat

**Comment by edmundlaugasson** [comment]
Kus koosolek füüsiliselt toimub? Mul on võimalik kohale tulla. Ei ole ka kellegi kontakti, et helistada, et seda uurida. Kirjutan ka siia.

**Comment by boamaod** [comment]
MTÜ Mondo ruumid Telliskivi 60A, juhatusest peaks mõned kl 16 paiku kohal olema juba, mina jõuan enne 16:30, täpne asukoht on minu teada siin:

* https://osm.org/go/0xLCYvJWP?m=

**Comment by infokujur** [comment]
Siin kergem muuta - hiljem kopeerime siia täisteksti:
https://docs.google.com/document/d/1uw11UBGOsYII9Jtgx-Pc2Zrj-cdZtJgZfPnVCwV83Vo

**Comment by infokujur** [comment]
See toimus ära. Järgmise kuulutame ikka jälle välja siin kanalis esimesena.
