### ISSUE TITLE
Koostööpartnerite kaardistamine

### ISSUE THREAD

**Issue by boamaod** [okestonia/esindus#5]
Meil on vaja kaardistada koostööpartnerid ja üles luua mingi koostööplatvorm, kus on jaotatud rollid ja vastutused. Üks eeskuju, millest õppida, on keskkonnaorganisatsioonid.

[Väärtused ja põhimõtted](http://ee.okfn.org/et/v22rtused-ja-p6him6tted/):
> Me tahame, et avatud teadmus kujuneks üldiselt käibel olevaks mõisteks, mis on sama loomulik ja arusaadav nagu on tänapäeval meie igapäevases tegevuses ja ühiskondlikes aruteludes on mõiste “roheline”.

Eestis on tegutsenud üle kümne aasta edukalt [Keskkonnaühenduste Koda](http://www.eko.org.ee/). Ma arvan, et me peaks looma midagi, mis täidab sarnaseid fuktsioone, sest avatud* väljal tegutsejad on hetkel väga killustunud ja ei toimu reaalset infovahetust, esimene eesmärk peaks olema tekitada ühine infoväli, siis saab edasist koostööd ja rollide jaotust plaanida.

Infovälja loomisel saab edukalt kasutada tehnilisi vahendeid, kui nt koosolekute protokollid jmt on avalikud, aga võimalik on leppida kokku ka mingis protokollis, mis sunnib meid rohkem agendasid klapitama.

Näiteks võiks sellised olla koostööpartnerid: [Wikimedia Eesti](https://ee.wikimedia.org/), [Avatud lähtekoodiga ja vaba tarkvara liit](http://alvatal.ee/), [ISOC Estonia](http://www.internetsociety.org/node/511296), aga nendega see kindlasti ei piirdu.

**Comment by infokujur** [comment]
@boamaod OKE-ga on juba liitunud mitu organisatsiooni. Vt https://github.com/okestonia/esindus/blob/master/members.md

#17 Nagu juhatuse koosolekul räägitud, siis Üldkoosolekul soovime tegutsejate ringi laieneda ning tuleb päevakorda. Saame selleks (community building, open leadership and cooperation) suuniseid Rufusega kohtumiselt #16.  Sulgen siin ja üldkoosoleku teemas arutame edasi #22
