### ISSUE TITLE
Open Knowledge Estonia home page development

### ISSUE THREAD

**Issue by tanelmallo** [okestonia/esindus#51]
Current pages at 
https://ee.okfn.org/en/ 
https://ee.okfn.org/et/
https://okfn.org/network/estonia/
need update. High expectations towards new management to move forward with this basic necessity in Autumn 2018.

**Comment by infokujur** [comment]
http://opendata.ee/

**Comment by infokujur** [comment]
Lisaks registreerimisankeet, mis on vale e-posti aadressiga.

**Comment by infokujur** [comment]
Hüüame infokirjas, kas keegi soovib panustada.

**Comment by infokujur** [comment]
Avaandmete päeval jäi see teema @peepkungas kanda. @infokujur annab sisendi projekti kohta.

**Comment by boamaod** [comment]
> Lisaks registreerimisankeet, mis on vale e-posti aadressiga.

See peaks parandatud olema. Mis seisus see kodulehe uuendamise plaan on üldse praegu?

**Comment by infokujur** [comment]
Keegi ei ole soovinud panustada. okee.ee sai teostatud _as is_ voog.ee platvormile.
