### ISSUE TITLE
Collaboration plans for new management

### ISSUE THREAD

**Issue by tanelmallo** [okestonia/esindus#52]
Review  organisations to work with, and decide if and how to participate, e.g.
1) Avatud valitsemise partnerluse koordineeriv kogu
2)

**Comment by infokujur** [comment]
@tanelmallo Vabaühenduste Liit koordineerib Ümarlauda, mis annab kolmanda sektori poolt sisendit koordineerivasse kogusse. Hea on sealt alustada ja selle kaudu edasi minna.

**Comment by infokujur** [comment]
Tegevused toimuvad valdkonna vedajate initsatiivil ja koostööl. Partnerid on kaardistatud teemadega tegelemise käigus.
