### ISSUE TITLE
avaliku sektori kulutused tarkvara ja riistvara peale

### ISSUE THREAD

**Issue by edmundlaugasson** [okestonia/esindus#57]
Eesti kui IT riik võiks omada ülevaadet kulutuste osas tarkvara peale. See on üks osa avaandmetest, mida seni väga keeruline kätte saada.

**Mida näidata?**
* tarkvarahanked
  * suletud lähtekoodiga
  * avatud lähtekoodiga
* arvutitöökohtade arv
* serverite arv
* kasutatav operatsioonisüsteem
  * töökohtadel
  * serveritel
* kasutatav kontroritarkvara
* muu tööks kasutatav tarkvara
* virtualiseerimistarkvara kasutamine
  * platvormi virtualiseerimine (nt VMware, Virtualbox, KVM, jne)
  * konteinerite kasutamine (nt docker, LXC, jne)
* peaks olema võimalik välja võtta määratud ajaperioodi lõikes
  * kulutatud raha töökohtade, serverite kaupa
  * ühe töökoha maksumus ja millise tarkvaraga
* ülevaade riistvara põhinäitajatest:
  * protsessorid
  * muutmälu (RAM)
  * kõvakettad

**Väljundkeskkond?** 
Mõned ideed:
* http://riigiraha.fin.ee/
* http://meieraha.ee/
* https://www.haridussilm.ee/ - siin oleks hea näidata haridusasutuste kaupa ja seda infot saab siis võtta sealt ühest kohast kuhu info kokku laekub. Kuna haridusasutustele tahetakse sageli lahendusi pakkuda ja selle veebikeskkonna näol on juba veebipõhine andmekogu olemas siis oleks see hea võimalus lisada sinna IKT kihid juurde.
  * näiteks on võimalus luua õpiobjektid virtuaalrakendusena (.ova) kuid oleks hea teada kui paljude haridusasutuste arvutid suudaksid vähemalt ühte virtuaalarvutit kasutada.

**Mõned võimalikud lahendused**
Asja mõte on, et kogu siin kirjeldatud info laekuks automaatselt ilma inimese vahelesekkumiseta. Seda kõik vaid ühe väikese programmikese paigaldamisega avaliku sektori asutustele ja seejärel on võimalik info automaatselt kokku koguda ja seda perioodiliselt.

Üks sobiv võiks olla tarkvara OCS Inventory - https://www.ocsinventory-ng.org/ - võimaldab koos GLPI'ga saada ülevaadet kogu avaliku sektori IKT varadest - https://glpi-project.org/
OCS Inventory vabad alternatiivid - https://alternativeto.net/software/ocsinventory-ng-org/?license=opensource

**Kasutegurid**
See annaks:
* võimalus nii riigil, KOV'il kui asutuse otsustajatel omada praktiliselt reaalajas infot kogu avaliku sektori IKT varade ja tarkvarade üle - see võiks olla rosinaks, miks võiks tahta, et riik omaks ülevaadet. Samas ei tohiks olla vastuväiteid kui riik omab ülevaadet oma varadest. Ka maksumaksja tahaks seda teada kuna tema raha eest ju lõppude lõpuks seda kõike ostetakse.
* riik saaks tagada võimalikult ühtlase taseme IKT valdkonnas kogu riigis
* omades operatiivset ülevaadet on võimalus langetada ka operatiivseid ja asjakohaseid otsuseid
* teadlastel, ettevõtetel jt on võimalus omakorda teha uuringuid ilma, et peaks kedagi tülitama ja säästes samal ajal aega jm ressursse, mida niigi napib ja kavandada tooteid, teenuseid jne. Kokkuvõttes aitaks see elavdada majandust.

**Mida seni tehtud?**
* 2015 mais suheldud Haridusministeeriumiga (Ingrid Jaggo) kui haridussilm.ee haldajaga - ei tulnud veel mõttega kaasa - väitis, et EHISes olevad IKT-ga seotud andmed on puudulikud ja ebaõiged. Siin see mõte oligi, et mitte võtta ebaõigeid andmeid EHISest vaid koguda need automaatselt kokku tarkvara abil.
* 2016 septembris suheldud EENetiga (Indrek Rokk) - hetkel puuduvad ressursid selle kõige käimapanekuks, haldamiseks. Ka arvati, et miks peaks üldse IKT andmeid avalikustama...
* praegune ülevaade kaootiline, näiteks
  * https://www.err.ee/597259/eesti-riik-maksab-microsoftile-miljoneid-eurosid-aastas
  * https://wiki.fsfe.org/Activities/EUMicrosoftContracts#Estonia
  * https://riigihanked.riik.ee/ ja otsida _tarkvara_, _litsents_, _Microsoft_ jms

**Comment by infokujur** [comment]
Tere!

Andmehulki on hea küsida siin:
https://github.com/okestonia/opendata-issue-tracker

Seal suurem auditoorium ning MKM jm vaatavad peale. Siin jääb ta ainult OKE enda inimestele silma. Neil neid andmeid ei ole :).

Maarja-Leena

**Comment by edmundlaugasson** [comment]
Lisatud - https://github.com/okestonia/opendata-issue-tracker/issues/149
