### ISSUE TITLE
Avaandmete päev / День Открытых Данных / Open Data Day 2019

### ISSUE THREAD

**Issue by boamaod** [okestonia/esindus#58]
Avaandmete päev on sel aastal laupäeval 2. märtsil. Mida ja kus me korraldame?

* https://opendataday.org/

**Comment by boamaod** [comment]
Küsisin Open Data Day korraldajate rahvusvahelisest listist infot selle aasta plaanide kohta. Ilmselt väga midagi ei muutu, aga huvitav teada.

**Comment by boamaod** [comment]
Reedel 1.03 on plaanimisel 6h töötubade seeria avaandmete portaaliga seoses, laupäeval 2.03 võimalikud kogukonnaüritused Tallinnas ja Narvas. On keegi huvitatud oma teemaga kaasa löömisest, abistamisest juba plaanitud ürituste korraldusel või korraldama veel mõnes linnas?

**Comment by infokujur** [comment]
Kohahoidja tehtud - hakkame sisu sisse valama.
Todo:
- 02.03 ruum ja esimesed 2 ettekannet

In process:
- 01.03 sisukujundamine. 6h suunatud pigem avaliku sekotori andmete avaldajatele - tehniline.

**Comment by boamaod** [comment]
Narvas toimub:

* https://www.facebook.com/events/386086558847033/

**Comment by boamaod** [comment]
Narva video:

* https://youtu.be/ANDw0NOVMBo

**Comment by infokujur** [comment]
Lisasin info siia: https://www.facebook.com/events/492678541258506/
Kui sellega on veel tegemist, siis palun avage uuesti.
