### ISSUE TITLE
Üldkoosolek ja võrgustumine 16.05.2019 15:00  // General meeting + networking 16.05.2019 from 3 pm

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#59]
OKEE üldkoosolek ja võrgustumisüritus 16. mail Saku Gastro pubis Rotermannis:  
**kell 15.00 - 16.30 üldkoosolek** 
teemad: 2018 majandusaasta aruande kinnitamine, põhikirja muutmine lihtsustamise eesmärgil, liikmeskonna aktiveerimine ja kasvatamine 
**kell 16.30 - 18.30 võrgustumine laiemas seltskonnas**
OKEE seniste saavutuste tutvustus, arutelu ühiskondlike valupunktide üle ning selle pinnalt lähiaastate prioriteetide ja plaanide ühine seadmine 

VÕRGUSTUMISÜRITUSE KUTSE: https://www.facebook.com/events/598390117332208/

Aita üritust korraldada: https://github.com/okestonia/esindus/projects/1

**Comment by teelepehk** [comment]
FOTOD ÜLDKOOSOLEKULT JA VÕRGUSTUMISELT: 
![20190516_164544](https://user-images.githubusercontent.com/38749818/57911053-6a43de80-788f-11e9-9549-48b5032c3464.jpg)
![20190516_164557](https://user-images.githubusercontent.com/38749818/57911054-6a43de80-788f-11e9-94a1-cf188f82b84d.jpg)
![20190516_170828](https://user-images.githubusercontent.com/38749818/57911057-6a43de80-788f-11e9-9aba-21276958ae4d.jpg)
![20190516_171112](https://user-images.githubusercontent.com/38749818/57911058-6a43de80-788f-11e9-9175-92bf475aaab7.jpg)
![20190516_171135](https://user-images.githubusercontent.com/38749818/57911060-6adc7500-788f-11e9-9ff2-67958ce692f7.jpg)
![20190516_171250](https://user-images.githubusercontent.com/38749818/57911061-6adc7500-788f-11e9-8807-b263d3d5690f.jpg)
![20190516_171315](https://user-images.githubusercontent.com/38749818/57911062-6adc7500-788f-11e9-99ec-4094505ac697.jpg)
![20190516_150824](https://user-images.githubusercontent.com/38749818/57911063-6adc7500-788f-11e9-8396-e4367d8a619c.jpg)
![20190516_151408](https://user-images.githubusercontent.com/38749818/57911064-6b750b80-788f-11e9-86bd-83b4c79f630e.jpg)
![20190516_151425](https://user-images.githubusercontent.com/38749818/57911065-6b750b80-788f-11e9-9b83-23b4d2d493cd.jpg)
![20190516_151622](https://user-images.githubusercontent.com/38749818/57911067-6c0da200-788f-11e9-9ffc-11edf49d4ba8.jpg)
