### ISSUE TITLE
Liikmete nimekiri

### ISSUE THREAD

**Issue by Hillehinsberg** [okestonia/esindus#6]
MTÜ Open Knowledge Estonia liikmeavalduse esitanud ja juhatuse otsusega  liikmeks vastu võetud on järgmised isikud ja organisatsioonid:

Siim Tuisk
Heikki Visnapuu
Risto Hinno
Adolfo Ruiz Calleja
Edmund Laugasson
 DataMe OÜ - esindaja Marko Vaik
Register OÜ - esindaja Peep Küngas
Andi Hektor
Oliver Kadak - Stats Unities OÜ esindajana
Antti Poikola - Open Knowledge Finland esindajana
Margo Loor - Citizen OS (Teeme Ära SA) esindajana
Vahur Puik
Hedi Mardisoo
Edgar Aronov

**Comment by boamaod** [comment]
Ma peaks saatma nüüd ikkagi kohe selge kirja kõigile neile umbes 30 inimesele, kes juba tahtsid liikmed olla asutamiskoosolekul, aga pole leidnud mahti avaldust esitada või pole saanud aru, mida me neilt ootame. Mitte kõik ei tea, mida ühe MTÜ liikmeks astumise juriidika täpselt tähendab, ja nad võivad vabalt eeldada, et tollest allkirjast piisaski. Kui ei piisanud, siis tuleks seda selgelt ütelda ja nõuda avaldust. Ja paluda vabandust, et nad seda bürokraatiat peavad taluma.

**Comment by boamaod** [comment]
Muide, vastav juhatuse koosoleku protokoll vajab ka allkirjastamist ja failina õigesse kohta üles laadimist.

**Comment by Hillehinsberg** [comment]
Tegin lihtsa  protokolli  ja jagasin teiega digidoc.ee keskkonnas.  - sinna oma pin-iga sisse logides peaks olema kaustas näha.
Andke teada, kui tekst vajab muutmist või kui  muu probleem (ei saa allkirjastada).

**Comment by Hillehinsberg** [comment]
Järgmiste liikmete vastuvõtu protokoll ootab juhatuse allkirju digidoc keskkonnas

**Comment by Hillehinsberg** [comment]
Järgmiste liikmete vastuvõtu protokoll  (0203 seisuga) ootab juhatuse allkirju digidoc keskkonnas

**Comment by tormi** [comment]
Teeks liikmete nimekirjale eraldi lehe, siis saaks selle muudatusi trackida. Andmetest võiks olemasolul kirjas olla ka liikme GitHub'i konto.

**Comment by puik** [comment]
Olen ka @tormi ettepanekuga nõus, et siinse *issue* redigeerimise asemel võiks dokumentide all olla eraldi nimekirja fail. Tegin [sellise faili pull requesti](https://github.com/okestonia/esindus/compare/master...puik:patch-1#diff-ff16894892ccb9df848016698b2937c5).

Aga nimekirjas peaksid olema ka asutajaliikmed, @Hillehinsberg.

**Comment by tormi** [comment]
#12 ei sobi? ;)

**Comment by puik** [comment]
Oi, muidugi sobiks. Keegi ei ole seda veel ametlikult masterisse lubanud?

**Comment by tormi** [comment]
Seal on mõned küsimused üleval:
- @boamaod, have you agreed about the language of this repo (english or estonian)?
- Is Maarja-Leena Saar = @infokujur correct? :)
