### ISSUE TITLE
Kuidas hakkame vastu EL autoriõiguse survestamistaktikale, mille kohta on Open Knowledge ütelnud, et see on "rünnak avatuse vastu"?

### ISSUE THREAD

**Issue by boamaod** [okestonia/esindus#60]
Meie organisatsiooni baasväärtus on [avatus](https://ee.okfn.org/et/v22rtused-ja-p6him6tted/) ning me seisame avatud andmete ja avatud taristu eest. Mida me teeme selleks, et Internet kui viimase poole sajandi olulisim avatud infotaristu projekt ei hävineks lühinägeliku seadusandluse tõttu? Meie organisatsiooni peakontor on meie väärtustest lähtuvalt võtnud [väga ühemõttelise seisukoha](https://blog.okfn.org/2019/02/14/eus-chilling-copyright-crackdown-an-attack-on-openness/) ning pöördunud Euroopa Parlamendi poole, et seda seadust vastu ei võetaks.

Eestis on seda teemat hoidnud üleval Internet Society ja Wikimedia Eesti, kriitiliselt on sõna võtnud ITL, ESLC, Inimõiguste Keskus, TÜ intellektuaalomandi õiguse professor Aleksei Kelli, vandeadvokaat ja autoriõiguse jurist Karmen Turk jt. Nüüd on 23. märtsiks plaanitud [meeleavaldus, et mõjutada lõpphääletust Euroopa Parlamendis](https://www.facebook.com/events/409020636530285/). Minu meelest oleks meie organisatsiooni jaoks läbikukkumine, kui me otsustaksime niivõrd olulises küsimuses jätta avatuse saatuse hooleks.

Meist sõltub midagi, kas te ei leia?

Et midagi siin kuidagi liiga segaseks ei jääks, siis tõlgin Open Knowledge tegevjuhi [Catherine Stihleri](https://en.wikipedia.org/wiki/Catherine_Stihler) tsitaadi täies mahus:

> See sügavat pettumust valmistav kokkulepe on rünnak avatuse vastu. Autoriõiguse survestamistaktikal on piirav mõju väljendusvabadusele üle kogu Euroopa Liidu. Me tahame võimestada inimesi, et nad ehitaks, jagaks ja taaskasutaks oma andmeid ja loodavat sisu vabalt ning avatult ning see samm töötab meie põhimõtte vastu.

> See ei täienda kodanike õigusei ja võib viia Euroopa muutumisele suletumaks ühiskonnaks — piirates seda, kuidas me jagame teadusuuringuid, mis võiks viia meditsiiniliste läbimurreteni või kuidas me jagama fakte, et võidelda "libauudiste" levikuga.

> Soovitan europarlamendi saadikutel tungivalt see ettepanek maha hääleteda ning võidelda tuleviku nimel, kus maailm on rohkem avatud.

Loodan, et ka meie kohalik rakuke leiab võimaluse seista avatuse eest!

**Comment by EvaLepik** [comment]
Head aatekaaslased, tegin natuke tõlketööd. 
https://blog.okfn.org/2019/02/14/eus-chilling-copyright-crackdown-an-attack-on-openness/
EL autoriõigusega represseerimine on rünnak avatuse vastu

EL läbirääkijad on saavutanud kokkuleppe autoriõiguse reformi asjus, mis on “rünnak avatuse vastu”, hoiatab OK Internationali uus tegevjuht. Catherine Stihler, endine europarlamendi saadik ja europarlamendi tarbijakaitsekomisjoni asepresident ütleb, et muudatused hakkavad piirama miljonite kasutajate internetivabadust.

Leping nõuab, et platvormid nagu Youtube, Twitter või Google News võtaksid maha kasutajate loodud sisu, mis võib rikkuda autoriõigust ning võtaksid kasutuse filtrid, mis takistaksid inimestel autoriõigusega kaitstud materjali üleslaadimist. See tähendab, et meemid, GIFid ja muusikaremiksid võidakse maha võtta, sest nende autoriõigus ei kuulu üleslaadijale. Seadus võib samuti piirata olulise uurimistöö ja faktide jagamist, lastes libauudistel vabalt levida.
Ette pandud muudatused lähevad järgmiseks Euroopa Parlamendi täiskogu hääletusele märtsis või aprillis.

Open Knowledge Internation on mittetulundusühing, mis võitleb avaandmete eest ja aitab erinevatel gruppidel andmetele ligi pääseda ning neid kasutada sotsiaalsete probleemide lahendamiseks. OKI tegevjuht Catherine Stihler ütles:
“See sügavat pettumust valmistav kokkulepe on rünnak avatuse vastu. Autoriõigusega survestamine viib sõnavabaduse külmutamiseni kogu Euroopa Liidus. Me tahame inimesi jõustada nende andmeid ja nende loodavat sisu vabalt ja avatult üles ehitama, jagama ning taaskasutama, aga see direktiiv käib selle põhimõtte vastu.
See ei edenda kodanike õigusi ning võib viia Euroopa ühiskonna suletuseni, piirates seda, kuidas me jagame uuringuid, mis võiksid viia meditsiiniliste läbimurreteni või kuidas me jagame fakte, et võidelda libauudiste levikuga.
Ma julgustan saadikuid seda seadust maha hääletama ja võitlema tuleviku eest, kus meie maailm on avatum.”
Rohkem infot selle kohta, kuidas aidata kaasa interneti päästmisele, leiad saidilt
saveyourinternet.eu 
Võid külastada ka petitsioonisaiti online petition ning lisada oma allkirja miljonitele teistele.

**Comment by boamaod** [comment]
Postitus on üleval siin, sulgen selle teema praegu, kuigi siin ilmselt on edasiseks aruteluks hulk põhimõttelisi ja olulisi küsimusi meie organisatsiooni võime kohta oma väärtuste eest seista või neist isegi elementaarses mõttes aru saada:

* https://ee.okfn.org/et/survestamine-avatuse-vastu/
