### ISSUE TITLE
Eesti asutuste informeerimine CC litsentside kasutamise teemal

### ISSUE THREAD

**Issue by boamaod** [okestonia/esindus#61]
Juhin tähelepanu, et Euroopa Komisjon on lubanud hakata kasutama mh CC0 litsentse eelkõige andmete jaoks:

* https://creativecommons.org/2019/04/02/european-commission-adopts-cc-by-and-cc0-for-sharing-information/

Mis on meie kava, kuidas viime CC litsentside korrektse kasutamise Eesti asutusteni, sj peaks selles kavas olema minu meelest loobumine senisest CC-BY vaikimisi nõudest andmete puhul ning eelistama komisjoni eeskujul CC0 litsentsi. Kas keegi tegeleb sellega juba ning võib plaanidest ja/või edulugudest raporteerida?

**Comment by boamaod** [comment]
Meil on CC litsentside tõlkimise issue siin: https://github.com/okestonia/opendata-issue-tracker/issues/94

**Comment by infokujur** [comment]
Tegevusi ja tegijat ei ole. Kuni aktiveerumiseni arhiveeritud.
