### ISSUE TITLE
Materjalid ette saata 

### ISSUE THREAD

**Issue by teelepehk** [okestonia/esindus#62]
2018 majandusaasta aruanne ja põhikirjamuudatuste mustand hiljemalt 1. mail liikmetele saata @infokujur

**Comment by alarirammo** [comment]
võin aidata põhikirja üle vaadata seadusesilmaga

**Comment by infokujur** [comment]
Juhtgrupilt ei ole tulnud seni konkreetseid ettepanekuid põhikirja osas.
Raha puudutav läks täna hommikul koos Uudiskirjaga:
https://github.com/okestonia/esindus/tree/master/dokumendid/Majandusaasta%20aruanded

Aga võib veel uuesti saata koos eraldi kutsega Üldkoosolekule.

**Comment by infokujur** [comment]
Praegune põhikiri on siin: https://github.com/okestonia/esindus/blob/master/dokumendid/p6hikiri_2016-10-27.md

Minu ettepanek oli võtta eesmärk ja lihtsustada - võttes eeskujuks MTÜ Kinoteater ja VÜL-i põhikiri. Põhjusel - kuna de facto käib koos üks grupp ja kahetasandiline juhtimine on praeguses aregustaadiumis liigne.

**Comment by boamaod** [comment]
> Minu ettepanek oli võtta eesmärk ja lihtsustada - võttes eeskujuks MTÜ Kinoteater ja VÜL-i põhikiri. Põhjusel - kuna de facto käib koos üks grupp ja kahetasandiline juhtimine on praeguses aregustaadiumis liigne.

Minu kogemus on selline, et meil on juba praegu vähemalt kolmetasandiline juhtimine ja infoliikumine, sj on märkimisväärselt eraldi a) tegev- ja projektijuhtimine (nt avaandmete riigihange, sellega seotud inimesed, tegevused, otsused), b) juhatuse tase, sj selle konverentskõned (mis on küllalt regulaarsed, aga siiski stiihilised ning mille päevakorrad, hääletused jmt on pigem hädapäraselt dokumenteeritud), c) liikmete tase, mis on pärast Slacki kasutamisest loobumist jäänud muudest protsessidest kõrvale.

Minu teada hakkasime 2018. aasta sügisest seda põhikirjas määratletud kahetasandilist eraldi nõukogu ja tegevjuhatusega juhtimist ka rakendama, kuigi ma ei saanud päris hästi aru, kuidas täpselt see toimus, sest ma pole dokumentatsiooni näinud. Kui me seda juba rakendame, siis kuidas on võimalik öelda, et see on "praeguses arengustaadiumis liigne"?

Ma lasen muidu hea meelega end veenda vastupidises, aga ma seni pole väga tugevaid argumente kuulnud ja kui me ei lahenda põhikirja muutmisega ühtegi konkreetset ja pakilist probleemi, siis võiks mu arvates sellest loobuda.

**Comment by infokujur** [comment]
Juhtimistasandid ongi selleks, et iga üks info virrvarrist saaks vajaliku kätte. Kuna tasandeid on palju ja infot vähe, siis just see tekitabki silod -> mott. Aga see oli ettepanek. Kui ollakse olukorraga rahul, siis ei ole vaja muuta.
