### ISSUE TITLE
Luua täidetav tabel OKI teemaliinidega 

### ISSUE THREAD

**Issue by teelepehk** [okestonia/esindus#64]
Ürituse eel levitada tabelit, millesse saavad osalejad märkida ideid, ressursse ja vajadusi. 
Enne üldkoosolekut juba laiali saata, et saaks täiendada. @teelepehk

**Comment by infokujur** [comment]
Hakkasin tabelit looma siia, ootan OKI vastust, kas topic areas kaardistusse on tulnud muutusi.
Kuna 2018 faili olime karja nimesid kirjutanud, siis lõin uue faili, kuhu toon järjepanu eelinfo sisse:
https://docs.google.com/spreadsheets/d/1K9sTohS1WAd4E7bmPEBT8b6CAgnTdQBrGuacSEQgj08

**Comment by infokujur** [comment]
OKI-lt ei ole täiendavat infot tulnud. Seega läheme selle tabeliga edasi.

**Comment by infokujur** [comment]
Eelmise korra kutse:
https://docs.google.com/forms/d/1KlJ3AI7LMDOriHIHyjYuL51M2b1u1YLunmHPnWC-IlY

**Comment by infokujur** [comment]
Tegin praeguse korra kutse ja panin need alad, kus on olnud mingidki tegevused.
https://docs.google.com/forms/d/1J7MUthNUutS5xWajwVxG8RO6AfmNEGC6dwqhPZAM8l4
Seda tuleks täita ürituse üldkutsega.
