### ISSUE TITLE
reganutele meeldetuletus; eelinfo ja kutsete levitamine 

### ISSUE THREAD

**Issue by teelepehk** [okestonia/esindus#65]
üldkoosoleku+võrgustumisürituse kohta OKEE liikmetele (uudiskirjaga) ja avatusega tegelevatele organisatsioonidele/inimestele saata (fb-s, tw-s, meilid)

korduskutse/meeldetuletus 14. või 15. mail + uudiskirjaga liitumise link: https://okfn.us15.list-manage.com/subscribe?u=ea70a6d7dbdc505b6738884fc&id=34414c8f72

**Comment by boamaod** [comment]
Mis organisatsioonid ja/või isikud selle teavituse saavad või on saanud, mis vormis?

**Comment by infokujur** [comment]
Uudiskiri läks välja täna hommikul. Selle kohta @tanelmallo kirjutas meile kõigile juba üle nädala tagasi. Sulle ka.

**Comment by teelepehk** [comment]
Lisaks lähevad kutsed neile, kes praegu väljaspool OKE-t, aga tegelevad suurte teemade/projektidega, milles vaja koostööd utsitada (rahandusministeeriumi KOVide rakendus, Smart City tegijad, Korruptsioonivaba Eesti jne). Kutsume neid võrgustumisossa, mitte üldkoosolekule.

**Comment by boamaod** [comment]
Lihtsalt neid organisatsioone, keda meie agenda võiks huvitada, on veel, nt Alvatal, Wikimedia, Isoc kui nimetada olulisemaid kodanikuühiskonna algatusi, aga ka AEF, AVP ümarlaud, e-Riigi akadeemia jt. Mõnedega neist on toimunud ka koostööläbirääkimisi ja juba seetõttu võiks kutsuda. Ehk võiks selle kokku leppida, kes kellele kutse saadab ja mis sisuga jne, sj ei peaks vist ühele mitu korda saatma. Õiguskantseleri büroole ja Riigikontrollile võiks ka saata, nad on eri punktides meie eesmärkide vastu huvi tundnud, nendega tegelenud või neid otseselt toetand. Ka Garage48 jm seltskonnad, kellega koos me oleme üritusi korraldanud. Ja millele me neid täpsemalt kutsume?

**Comment by teelepehk** [comment]
Sellele üritusele kutsume: https://www.facebook.com/events/598390117332208/
