### ISSUE TITLE
OKI teemaliinide tabel kohapeal täidetavaks

### ISSUE THREAD

**Issue by teelepehk** [okestonia/esindus#67]
Suure väljatrükina seinale panna? Või iga teema erladi A4-le, mille peale saab igaüks kleebikuga oma mõtteid lisada. 
Või kuvada ekraanile ja täita kohapeal arvutis? 
Puutetundlik ekraan oleks kõige parem muidugi ;)

**Comment by teelepehk** [comment]
@infokujur , mida arvad sellest: OKI teemad kirjutaksin igaühe suurelt eraldi A4-le, saame ruumis seintele panna või suurele lauale, igaüks saab kleebikuga oma mõtteid juurde lisada. Selline lihtne lahendus, siis pole vaja tabelit printimiseks kujundada. Lisaks saame ka ekraanile seda kogutabelit lasta, et 2019 kaardistuse väljad täita.

**Comment by infokujur** [comment]
Ja! Väga hea. Praegu just mõtlesin, kuidas ma homme printima hakkan. Kleebikud on mu lemmikud.
