### ISSUE TITLE
Materjalid aasta tegevuste esitlemiseks.

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#69]

**Comment by infokujur** [comment]
Panin oma slaidi kokku: https://docs.google.com/presentation/d/1UMt7Th-zUJtlwdUId4egLgxLInii6L2dGKKESIAjhS4
@vaikmarko @tanelmallo @teelepehk - kas soovite ka siia midagi veel lisada?

**Comment by tanelmallo** [comment]
Täiendasin seda avaslaidi, kava ja logoga.
Möödunud korral pakkusime välja ka üle veebi osalemise, selleks on meil Jitsi kanal https://meet.jit.si/okeeyldkoosolek
Kui soovime, võime ka seekord nt koosoleku alguses sotsiaalmeediasse postida, et see võimalus on olemas. Äkki keegi ühinebki! Üleüldise põhimõttena oleks õige pakkuda seda kogu aeg.

**Comment by infokujur** [comment]
Panin veel infot juurde, et meelest ei läheks:
https://docs.google.com/presentation/d/1UMt7Th-zUJtlwdUId4egLgxLInii6L2dGKKESIAjhS4
