### ISSUE TITLE
Avaandmete päeva / Open Data Day tähistamine

### ISSUE THREAD

**Issue by boamaod** [okestonia/esindus#7]
Sel aasta on [Open Data Day](http://opendataday.org/) 4. märtsil, eelmisel aastal toimus Tartus:

* http://www.opendata.ee/2016-03-14/tartu-linna-andmekogude-avamine/

Sel aastal on Tartus ürituse korraldamiseks läbirääkimised Wikimedia jt partneritega juba alanud, kas keegi tahaks veel korralduses osaleda?

**Comment by emenov** [comment]
Olen valmis aitama, sest teema seondub minu uurimustööga. Kas ürituse kava on juba koos ja oled mini granti taotluse esitanud? https://blog.okfn.org/2017/01/25/announcing-the-2017-international-open-data-day-mini-grants-scheme/

**Comment by boamaod** [comment]
Ma olen suhelnud sel teemal TÜ infoühiskonna keskusega, kes tahaks natuke hiljem märtsis teha meedia teemade häkatoni (esialgu _post truth_ sildi all) ja võimalik, et saaks avaandmete päeva teha selle n-ö eelüritusena, sest tõepõhja teemad seonduvat otseselt andmete ja faktide jmt asjadega. Ma võtan nendega uuesti ühendust ja vaatan, mis seis selle asjaga on, sest ma lubasin eelmisel nädalal neid sellega aidata, aga mul polnud aega.

**Comment by emenov** [comment]
Ma arutasin teemat oma itaallasest kolleegiga, kes on osalenud selleteemalistel üritustel Itaalias jm ning ta pakkus välja mõned ideed, mida võiks ürituse raames korraldada:

1. kutsuda esinema OKFN või ODI ekspert, kasvõi Skypes;
2. kutsuda esinema teemaga seotud akadeemik või valitsusametnik;
3. viia läbi avalik arutelu teemal kasulikud avaandmed: mis andmed meil on vs milliseid andmeid oleks meil kasulik koguda;
4. viia läbi väike hackathon teemal "Meil on sellised andmebaasid ja meile oleks kasulik teha need avalikult kättesaadavaks sobivas formaadis" või "Mida oleks võimalik teha nende avaandmetega, mis meil on juba olemas? Visualiseerida, teha statistikat jne.

**Comment by Hillehinsberg** [comment]
Aitäh! -  üritamegi käima lükata eelkõige Su soovituse nr 3 - mis on kasutajate poolt  vaadates esmavalikud - milliseid andmeid tuleb saada avatuks (Open Data indexi  teemakategooriate põhjal).

**Comment by boamaod** [comment]
@emenov Aga saame Tartus see nädal sel teemal kokku korra mingi seltskonnaga? Muide, veidi tausta on ka https://github.com/okestonia/esindus/issues/9#issuecomment-277711624

**Comment by boamaod** [comment]
I'll meet with some people from Tartu University research administration office today after 14, and we meet with activists after 18 for some discussion about the plan. Contact me if you want to join.

**Comment by boamaod** [comment]
Now we have a dedicated repository, file issues there, if you have ideas: https://github.com/okestonia/opendataday

**Comment by infokujur** [comment]
@boamaod Kas soovid siia lõppu veel mõne kommentaari kirjutada. Sai tähistatud ja tagasiside oli hea. Panen praegu suletuks, kui jätkutegevusi (uute tegevustega palun ava uus issue) üleval ei ole.
