### ISSUE TITLE
OKEE uue põhikirja mustand

### ISSUE THREAD

**Issue by tanelmallo** [okestonia/esindus#71]
MTÜ OPEN KNOWLEDGE ESTONIA PÕHIKIRI

1. MTÜ Open Knowledge Estonia asub Tallinnas, selle põhieesmärk on tagada info vaba kättesaadavus kõigis ühiskonna kihtides, nii era- kui avalikus sektoris, ning aidata sellega kaasa avatud teadmusühiskonna arengule. Ühing seisab oma liikmete ühiste huvide eest avatud teadmuse edendamisel, koondab huvitatud kogukondi ja nende kogemust, aitab ellu viia algatusi ja projekte, kaasab vajadusel avalikkust — ning juurutab andmete kasutamise, jagamise ja väärindamise viise, mis loovad jätkusuutlikku raamistikku innovatsiooniks ja ettevõtluseks valdkondades andmeteadusest loomemajanduseni ning toetavad avatud valitsemise eesmärkide saavutamist riigi ja omavalitsuse tasemel.

2. Liikmeks võib olla igaüks, kuni ta lööb kaasa eesmärgi saavutamisel.
3. Liikme õigused ja kohustused kehtestab üldkoosolek.
4. Liikme vastuvõtmise ja väljaarvamise korraldab juhatus.
5. Üldkoosolek kutsutakse kokku e-kirjaga, otsustusvõime ei sõltu osalejate arvust.
6. Juhatusse valitakse 1-5 liiget kolmeks aastaks.
7. Lõpetamisel antakse vara tulumaksusoodustusega või avaõiguslikule organisatsioonile.

**Comment by tanelmallo** [comment]
- põhikirja lihtsustamise eesmärk on organisatsiooni tööd lihtsustada.
- reaalsuses koosneb organisatsioon aktiivsetest liikmetest, kes ajavad asju; nõukogu ei ole praktiliselt vajalik.
- kontrollida, kas põhikirjas saab olla, et üldkoosoleku otsustusvõime ei sõltu osalejate arvust.
- täna alustame diskussiooni, uue põhikirja võtame vastu järgmisel üldkoosolekul. Arutelu kuni järgmise üldkoosolekuni toimub siin.

**Comment by infokujur** [comment]
Vastus tuli, et kinnitatud.
