### ISSUE TITLE
ERMile, Muinsuskaitseametile, T.Tootsile ja teistele ringkiri laastutabloo avamisürituse kontseptsiooniga

### ISSUE THREAD

**Issue by teelepehk** [okestonia/esindus#74]
OKE eelistab 22. novembrit, siis saab ERM digidisko korraldada

**Comment by tanelmallo** [comment]
Üleskutse draft siin: https://docs.google.com/document/d/1ef07dsYuKWVXc704-F0vU77BJ5v8Yax3kvg6gnGw1wo/edit

**Comment by infokujur** [comment]
Ja!

**Comment by teelepehk** [comment]
Ägeda andmesündmuse kontseptsioon, mis ERMi, Timo Tootsi ja Martin Adamsooga läbi räägitud: https://docs.google.com/document/d/15GrpojrZOvpwNcEE_E3izGWLpUzgiqExB98gJVJjS0s/edit

**Comment by infokujur** [comment]
Siia sai üles märgitud, mis toimus:
https://docs.google.com/document/d/1TNsgDvHXNBHmbw9yFOrtS3inWRwJlYlbbL3MHjAcajo/edit
