### ISSUE TITLE
põhikirja muutmise protseduur ette valmistada + protokolli mustand valmis teha

### ISSUE THREAD

**Issue by teelepehk** [okestonia/esindus#78]
**Põhikirja muutmine:** 
1. kuna OKE kehtivas põhikirjas pole üldkoosoleku hääleõiguse kohta midagi kirjas, lähtume MTÜ-de seadusest (https://www.riigiteataja.ee/akt/MT%C3%9CS), mille kohaselt 
2. üldkoosolekul oleks kena selgitada üle, miks põhikirja vaja muuta ning lugeda ette uue põhikirja mustandile tulnud ettepanekud (praeguse seisuga pole neid siin: https://docs.google.com/document/d/1f0WnCvP9mt-tIL3vcOkKhIF_k-GATSz2ShzESgwtlZs/edit), lisaks koguda kohapeal tagasisidet. Kui tagasisidet pole, siis hääletada uue põhikirja vastuvõtmise üle.  
3. Üldkoosoleku otsus on vastu võetud, kui selle poolt hääletab üle poole koosolekus osalenud mittetulundusühingu liikmetest või nende esindajatest. 

**Protokollimise nõuded seadusest:** 
(*) Üldkoosolek protokollitakse. Protokolli kantakse üldkoosoleku toimumise aeg ja koht, üldkoosoleku päevakord, hääletustulemused ja vastuvõetud otsused ning muud üldkoosolekul tähtsust omavad asjaolud. Protokolli kantakse ka üldkoosoleku otsuse suhtes eriarvamusele jäänud liikme nõudel tema eriarvamuse sisu. Protokollile kirjutavad alla üldkoosoleku juhataja ja protokollija. Eriarvamusele kirjutab alla selle esitanud isik. Protokolli lahutamatuks lisaks on üldkoosolekust osavõtnute nimekiri koos igaühe allkirjaga ning üldkoosolekule esitatud kirjalikud ettepanekud ja avaldused. 
Üldkoosoleku protokolli näidis: https://heakodanik.ee/sites/default/files/files/%C3%9Cldkoosoleku%20protokolli%20n%C3%A4idis.doc 

(*) Osalejate nimekiri - kõige lihtsam oleks lasta igaühel kohapeal nimekiri (või kohalolu-leht) digiallkirjastada, kuna äriregistrile saame siis digidoci esitada (mitte ei pea originaallehte postiga saatma).
  
(*) Pärast 14 päeva möödumist üldkoosoleku lõppemisest peab protokoll olema liikmetele kättesaadav. Liikmel on õigus saada üldkoosoleku protokolli või selle osa ärakirja.

Teele hoolitseb protokolli ja osalejate digiallkirjade eest kohapeal.

**Comment by infokujur** [comment]
Link protokollile siia ka: https://docs.google.com/document/d/1VBG_i02sVUI1p358qlq8azSY-or7Mg1mm1ZagQc4S4E/edit

**Comment by infokujur** [comment]
Kandeavaaldus tehtud, kui kinnitatakse, siis uuendame dokumendid ka siin.

**Comment by teelepehk** [comment]
Panin allkirjalehe registriosakonna suunas teele!

**Comment by infokujur** [comment]
Vastus tuli, et kinnitatud.
