### ISSUE TITLE
Litsentsist

### ISSUE THREAD

**Issue by tormi** [okestonia/esindus#8]
Tere!

Esinduse repole on lisatud [lisentsitingimused](https://github.com/okestonia/esindus/blob/master/LICENSE), mis käsitlevad tarkvara:

> This is free and unencumbered software released into the public domain.

Tundub, et selles repos tarkvara siiski ei teki, seepärast oleks ehk mõistlikum kasutada [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) litsentsitingimusi ;)

**Comment by boamaod** [comment]
Varamu loomisel vist polnud CC0 vaikimisi valitavate litsentside hulgas, soovitus on igati loogiline, asendasin.
