### ISSUE TITLE
Avaandmete päev 2020?

### ISSUE THREAD

**Issue by infokujur** [okestonia/esindus#81]
Kas? Kes? Kus?

Nüüd on hea aeg end üles anda.

Siit saab veebi: https://github.com/okfn/opendataday/tree/master/content

**Comment by boamaod** [comment]
Here is a localized version of the web:

* https://github.com/okestonia/opendataday (http://opendata.ee/opendataday/et/)

Vitaly who presented at Open Data Day in Narva last year showed interest in doing something this year too.

**Comment by tkardi** [comment]
Is there something going to be happening in Tartu aswell?

**Comment by boamaod** [comment]
There seems to be an event in Tartu:

> Estonias School of Data hosts an environmental data meetup on March 3rd in Tartu. We aim to bring together both environmental data creators and holders as well as data journalists, advocates and others bedazzled by environmental data, and take a collective look on currently existings enironmental data in Estonia as well as access to it. Thanks to Open Knowledge Estonias partnership with Ministery of Economy, the data meetup will offer an unique possibility to actually open up new important datasets by direct nudging of national open data work group. The environmental data meetup also celebrates World Open Data Day with events held worldwide. 
Specific location to be announced.

* https://www.facebook.com/events/948883462173909/

**Comment by boamaod** [comment]
Anybody wants to work on FOI portal during Open Data Day weekend? I have personal interest to get it running and can meet up for mini-hackathon. There is [ISOC](https://www.isoc.ee/) meeting in LIFT99 on 7th from 1 pm to 3 pm and this might be used for Open Data Day discussions or FOI portal hacking, if anybody's interested. Also discussing historical FOI requests related to [Zonefile published last year](https://blog.zone.ee/2019/06/25/ee-tsoonifail-lopuks-avalik-aga-mis-hinnaga/) might be a relevant topic.
