### ISSUE TITLE
 Feb 6th informal meetup with members and board

### ISSUE THREAD

**Issue by Hillehinsberg** [okestonia/esindus#9]
We get together on Monday, February 6 at 16.00 hrs at Tallinn University (convene in the lobby of Astra building at 15.55 or come directly to room 133- Mare from the sea-facing side).

The aim is to  get things moving and make an action plan for Open Knowledge Estonia.
Items to discuss:
1. short term business ( couple of months)
-  March 4th, International Open Data Day - what we want to see happen and organise ourselves?
- other days, conferences, workshops - where we want to contribute? e.g. Tartu hackathon on post truth media sphere; e.g. Garage48 hackathon in May etc.
- Digital Single Market conference in July and  MyData conference in August - how is OK-EE involved.

2. medium term business (2017)
- collecting gaps and sorting out priorities  in  EST public data that should be opened
- how to engage partners  ( in Estonia and internationally) and identify common aims and initiatives, e.g. need for Open Data Handbook translation and dissemination? or  how to build the  "business case" and bring out economic impact of OD?

**Comment by boamaod** [comment]
I think there is a point in creating materials from OD community to community plus governement, businesses about how to use OD, what we expect etc. Currently there are only docs by government which are quite ok and cover much on OD handbook, but we probably need to split it into pieces and write materials oriented directly to different target groups. I think OD handbook itself is not relevant format for us though, this basic information is already in https://opendata.riik.ee/roheline-raamat and elsewhere.

**Comment by edmundlaugasson** [comment]
On Monday, 6th February I have lectures and cannot participate. If there is anything where I can engage students then I can help more efficiently. Looks like [IT College is organizing own hackathon](http://www.itcollege.ee/siseturvalisuse-hakaton/).

**Comment by infokujur** [comment]
- collecting gaps and sorting out priorities in EST public data that should be opened

I'll  add here two resources:

- **Roof terms and principles from G8 Open Data Charter**
https://www.gov.uk/government/publications/open-data-charter/g8-open-data-charter-and-technical-annex

- Concrete valuation of a situation in Estonia. We could map first our situation for **OpenData Index** and then prioritize missing datasets, what could fill the gaps. This how we get initial demand list.
http://global.survey.okfn.org/

- Extra input from the community.
Gather extra datasets what are not listed above and add to our demand list.

**Comment by Hillehinsberg** [comment]
Memo Feb 6th meeting

People present:
Antti Poikola
Tanel Mällo
Märt Põder
Maarja-Leena Saar
Geoffroy  Berson
Adolfo Ruiz
Andres Kütt
Siim Tuisk

Events coming up
**March 4th Open Data Day!**
Tartu University  (Media department and computer studies) holds event son post truth in spring. 
Märt will be involved to organize a pre-event on March 4.
Poliitika.guru blog and Tõnu Runnel? Data journalism actors? maybe Faktabaari share their method of checking media  articles?

NB! Good day to publish  the initial backlog : publish the site with initial input already gathered by that time.
- which datasets are priority for users? how to get the seed going? take the categories and start digging out gaps. We will crowdsource  input and let gov  people cross-check if data is there and in good quality.
- lets use the excel that was collected at Tartu hackathon
- What to do with APIs that are not made public?: we gather information and publish!
- categories might evolve into specific issues, each will  have a community of contributors

March 30,  Internet Day event:  Märt represents IOS and 5th freedom included in topics.

**MyData Conference** (Helsinki and Tallinn cross-border cooperation) in August
- - in Tallinn the day is more academic, questions of personal data
 - call for proposals for academic submissions will open soon.  Intl OK network involved (probably 10 - 15 persons, e.g Rufus Pollock)
- should we organize OK community meetup separately?
- regular weekly "talgud" meetups  (16.00 - 18.00 hrs on Thursdays in TLU) for volunteers/crowdsourced effort  in doing workbits for the conference.
**Digital Single Market Conference**
- organized by gov, OK-EE members are in the content-formulating group. Rolls around ownership of data. Tanel will share regular updates on GitHub.

medium term activities

1. stakeholders mapping
a- contact  people by topic (especially those categories which do not have any input). e.g. Keegan - will provide his list) and Kalvet  and Krimmer from TTU 
b-  Andres will bug gov info reps to join the issues and provide feedback. e.g. GeekOut data analysts who know which data is available

**Comment by boamaod** [comment]
Communication channels and media plan is currently discussed under issue #4, please give your suggestions and arguments there!

**Comment by infokujur** [comment]
All the topics have been moved further. Overview about activities made first year will be talked in General Meeting #22
